# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-08-07 10:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_scoresheetaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoresheetaddress',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
