# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-08-24 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldreference',
            name='context',
            field=models.CharField(blank=True, choices=[('TRAINING_DAILY_MANAGEMENT', 'TRAINING_DAILY_MANAGEMENT'), ('TRAINING_PROPOSAL_MANAGEMENT', 'TRAINING_PROPOSAL_MANAGEMENT'), ('TRAINING_PGRM_ENCODING_PERIOD', 'TRAINING_PGRM_ENCODING_PERIOD'), ('MINI_TRAINING_DAILY_MANAGEMENT', 'MINI_TRAINING_DAILY_MANAGEMENT'), ('MINI_TRAINING_PROPOSAL_MANAGEMENT', 'MINI_TRAINING_PROPOSAL_MANAGEMENT'), ('MINI_TRAINING_PGRM_ENCODING_PERIOD', 'MINI_TRAINING_PGRM_ENCODING_PERIOD'), ('GROUP_DAILY_MANAGEMENT', 'GROUP_DAILY_MANAGEMENT'), ('GROUP_PROPOSAL_MANAGEMENT', 'GROUP_PROPOSAL_MANAGEMENT'), ('GROUP_PGRM_ENCODING_PERIOD', 'GROUP_PGRM_ENCODING_PERIOD')], max_length=50),
        ),
    ]
