# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-08-30 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('rules_management', '0002_auto_20180824_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldreference',
            name='groups',
            field=models.ManyToManyField(blank=True, to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='fieldreference',
            name='permissions',
            field=models.ManyToManyField(blank=True, to='auth.Permission'),
        ),
    ]
