# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-06 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dissertation', '0032_auto_20171010_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dissertationupdate',
            name='justification',
            field=models.TextField(blank=True),
        ),
    ]
