# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-03 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0016_auto_20170410_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='changed',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
