# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-21 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0016_auto_20170410_1318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='language',
            name='id',
        ),
        migrations.AlterField(
            model_name='language',
            name='code',
            field=models.CharField(max_length=4, primary_key=True, serialize=False),
        ),
    ]
