# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-21 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0017_auto_20180321_1107'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE public.reference_language DROP CONSTRAINT  reference_language_code_226677c1_pk"
        ),
        migrations.AddField(
            model_name='language',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='language',
            name='code',
            field=models.CharField(max_length=4, unique=True),
        ),
    ]
