# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-08-10 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0019_auto_20180807_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='changed',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
