# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-06 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attribution', '0017_auto_20171027_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorapplication',
            name='course_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tutorapplication',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
