# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-02 12:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0201_auto_20171204_1659'),
        ('attribution', '0017_auto_20171027_1706')
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attributionnew',
            options={'permissions': (('can_access_attribution_application', 'Can access attribution application'),)},
        ),
    ]
