# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-07 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attribution', '0018_auto_20171206_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorapplication',
            name='last_changed',
            field=models.DateTimeField(null=True),
        ),
    ]
