# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-05 07:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attribution', '0019_auto_20180103_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributionnew',
            name='summary_responsible',
            field=models.BooleanField(default=False),
        ),
    ]
