# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-08 14:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attribution', '0020_auto_20180105_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributionnew',
            name='substitute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='attribution.AttributionNew'),
        ),
    ]
