# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-16 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attribution', '0022_auto_20180115_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribution',
            name='deleted_new',
            field=models.DateTimeField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='attributionchargenew',
            name='deleted_new',
            field=models.DateTimeField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='attributionnew',
            name='deleted_new',
            field=models.DateTimeField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='tutorapplication',
            name='deleted_new',
            field=models.DateTimeField(blank=True, db_index=True, default=None, null=True),
        ),
    ]
