# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-16 09:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attribution', '0024_auto_20180116_1034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attribution',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='attributionchargenew',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='attributionnew',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='tutorapplication',
            name='deleted',
        ),
    ]
