# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-16 09:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attribution', '0025_auto_20180116_1052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attribution',
            old_name='deleted_new',
            new_name='deleted',
        ),
        migrations.RenameField(
            model_name='attributionchargenew',
            old_name='deleted_new',
            new_name='deleted',
        ),
        migrations.RenameField(
            model_name='attributionnew',
            old_name='deleted_new',
            new_name='deleted',
        ),
        migrations.RenameField(
            model_name='tutorapplication',
            old_name='deleted_new',
            new_name='deleted',
        ),
    ]
