# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-29 13:41
from __future__ import unicode_literals

from django.db import migrations

# WARNING !!!! This file is very important to ensure the consistancy !
# Don't FORGET to use it if you merge migration file


class Migration(migrations.Migration):

    dependencies = [
        ('attribution', '0028_auto_20180129_1308'),
    ]

    operations = [
        migrations.RunSQL(
            """CREATE UNIQUE INDEX attributionnew_learningcontaineryearid_tutorid_function_deleted
                    ON attribution_attributionnew
                (learning_container_year_id, tutor_id, function, coalesce(deleted,'2000-01-01'));""",
            "DROP INDEX attributionnew_learningcontaineryearid_tutorid_function_deleted"
        ),
        migrations.RunSQL(
            """CREATE UNIQUE INDEX tutorapplication_learningcontaineryearid_tutorid_function_deleted
                    ON attribution_tutorapplication
                (learning_container_year_id, tutor_id, function, coalesce(deleted,'2000-01-01'));""",
            "DROP INDEX tutorapplication_learningcontaineryearid_tutorid_function_deleted"
        ),
    ]
