# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-27 12:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attribution', '0030_auto_20180228_0856'),
    ]

    operations = [
        # Remove all deleted records physically
        migrations.RunSQL("DELETE FROM attribution_attribution WHERE deleted is not null"),
        migrations.RunSQL("DELETE FROM attribution_attributionchargenew WHERE deleted is not null"),
        migrations.RunSQL("DELETE FROM attribution_attributionnew WHERE deleted is not null"),
        migrations.RunSQL("DELETE FROM attribution_tutorapplication WHERE deleted is not null"),
        # Remove unique index
        migrations.RunSQL("DROP INDEX IF EXISTS attributionnew_learningcontaineryearid_tutorid_function_deleted"),
        migrations.RunSQL("DROP INDEX IF EXISTS tutorapplication_learningcontaineryearid_tutorid_function_deleted"),
    ]
