# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-27 13:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attribution', '0032_auto_20180327_1458'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tutorapplication',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='attribution',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='attributionchargenew',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='attributionnew',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='tutorapplication',
            name='deleted',
        ),
    ]
