# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-10-23 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attribution', '0034_auto_20180807_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributionchargenew',
            name='changed',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
