# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-11 12:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0016_auto_20170410_1318'),
        ('base', '0164_educationgroupyear_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationGroupLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('PRIMARY_LANGUAGE', 'PRIMARY_LANGUAGE')], max_length=255)),
                ('order', models.IntegerField()),
            ],
            options={
                'permissions': (('can_access_education_group', 'Can access education_group'),),
            },
        ),
        migrations.AddField(
            model_name='educationgroupyear',
            name='language_association',
            field=models.CharField(blank=True, choices=[('OR', 'OR'), ('AND', 'AND')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='educationgrouplanguage',
            name='education_group_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.EducationGroupYear'),
        ),
        migrations.AddField(
            model_name='educationgrouplanguage',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reference.Language'),
        ),
    ]
