# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-31 13:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0171_auto_20171017_1132'),
    ]

    operations = [
        migrations.RunSQL(
            [(
             "INSERT INTO osis_common_messagetemplate (reference, subject, template, format, language) VALUES (%s, %s, %s, %s, %s);",
             ['learning_unit_year_deletion_html',
              'Suppression d\u0027une unité d\u0027enseignement',
              '<p>{% autoescape off %}</p>\r\n\r\n<p>Bonjour {{ first_name }} {{ last_name }},<br />\r\nCeci est un message automatique g\u00e9n\u00e9r\u00e9 par le serveur OSIS – Merci de ne pas y r\u00e9pondre.<br />\r\n<br />\r\nVous avez demandé la suppression de l\u0027UE {{ learning_unit }} à partir de l\u0027année {{ academic_year }}:<br />\r\n<lu><uli>Les partims suivants {{ partims }} ont été supprimés pour les années de validité {{ partims_start_date }} à {{ partims_end_date }}</uli><uli>Les classes suivantes {{ classes }} ont été supprimées pour les années de validité {{ classes_start_date }} à {{ classes_end_date }}</uli><uli>L\u0027UE a été supprimée pour les années de validité {{ ue_start_date }} à {{ ue_end_date }}</uli><ul>\r\n<br />\r\n\r\nCordialement,<br />\r\nOsis UCLouvain<br /></p>\r\n{% endautoescape %}',
              'HTML',
              'fr-be'])],
        ),
    ]