# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-25 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0171_auto_20171017_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationgroupyear',
            name='code_scs',
            field=models.CharField(db_index=True, max_length=15, null=True),
        ),
    ]
