# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-27 14:46
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0172_learningunityear_quadrimester'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningcomponentyear',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, null=True),
        ),
        migrations.AddField(
            model_name='learningcontaineryear',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, null=True),
        ),
    ]
