# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-27 15:02
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0174_auto_20171027_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningcomponentyear',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='learningcontaineryear',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
