# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-27 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0175_auto_20171027_1702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learningunityear',
            name='in_charge',
        ),
        migrations.RemoveField(
            model_name='learningunityear',
            name='team',
        ),
        migrations.RemoveField(
            model_name='learningunityear',
            name='vacant',
        ),
        migrations.AddField(
            model_name='learningcontaineryear',
            name='in_charge',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='learningcontaineryear',
            name='team',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='learningcontaineryear',
            name='vacant',
            field=models.BooleanField(default=False),
        ),
    ]
