# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-30 10:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0175_auto_20171027_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningcomponentyear',
            name='volume_declared_vacant',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True),
        ),
    ]
