# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-31 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0177_learningcomponentyear_volume_declared_vacant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='learningcontaineryear',
            old_name='vacant',
            new_name='is_vacant',
        ),
        migrations.AddField(
            model_name='learningcontaineryear',
            name='type_declaration_vacant',
            field=models.CharField(blank=True, choices=[('WITHOUT_OBJECT', 'WITHOUT_OBJECT'), ('RESEVED_FOR_INTERNS', 'RESEVED_FOR_INTERNS'), ('OPEN_FOR_EXTERNS', 'OPEN_FOR_EXTERNS'), ('EXCEPTIONAL_PROCEDURE', 'EXCEPTIONAL_PROCEDURE'), ('VACANT_NOT_PUBLISH', 'VACANT_NOT_PUBLISH'), ('DO_NOT_ASSIGN', 'DO_NOT_ASSIGN')], max_length=100, null=True),
        ),
    ]
