# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-31 07:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0177_learningcomponentyear_volume_declared_vacant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='learningcontaineryear',
            old_name='vacant',
            new_name='is_vacant',
        ),
        migrations.AddField(
            model_name='learningcontaineryear',
            name='type_declaration_vacant',
            field=models.CharField(blank=True, choices=[('WITHOUT_OBJECT', 'WITHOUT_OBJECT'), ('INTERNAL', 'INTERNAL'), ('EXTERNAL', 'EXTERNAL'), ('EXCEPTIONAL_PROCEDURE', 'EXCEPTIONAL_PROCEDURE'), ('DECLARED_NOT_VACANT', 'DECLARED_NOT_VACANT'), ('DO_NOT_ASSIGN', 'DO_NOT_ASSIGN')], max_length=100, null=True),
        ),
    ]
