# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-02 13:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0178_auto_20171031_1544'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mandatary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, max_length=100, null=True)),
                ('changed', models.DateTimeField(auto_now=True, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Mandate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, max_length=100, null=True)),
                ('changed', models.DateTimeField(auto_now=True, null=True)),
                ('function', models.CharField(choices=[('PRESIDENT', 'PRESIDENT'), ('SECRETARY', 'SECRETARY'), ('SIGNATORY', 'SIGNATORY')], max_length=20)),
                ('qualification', models.CharField(blank=True, max_length=50, null=True)),
                ('education_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.EducationGroup')),
            ],
        ),
        migrations.AddField(
            model_name='mandatary',
            name='mandate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Mandate'),
        ),
        migrations.AddField(
            model_name='mandatary',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Person'),
        ),
    ]
