# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-03 14:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0178_auto_20171031_1544'),
        ('base', '0172_auto_20171031_1401'),
    ]

    operations = [
    ]
