# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-06 07:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0179_mandate'),
    ]

    operations = [
        migrations.AddField(
            model_name='offeryearcalendar',
            name='education_group_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.EducationGroupYear'),
        ),
        migrations.AlterField(
            model_name='offeryearcalendar',
            name='start_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='offeryearcalendar',
            name='end_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
