# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-13 10:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0181_removed_nullable_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='programmanager',
            name='education_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.EducationGroup'),
        ),
    ]
