# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-05 10:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0179_merge_20171103_1501'),
        ('base', '0181_removed_nullable_uuid'),
    ]

    operations = [
    ]
