# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-06 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0182_programmanager_education_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationgroupyear',
            name='credits',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='educationgroupyear',
            name='partial_acronym',
            field=models.CharField(db_index=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='educationgroupyear',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='educationgroupyear',
            name='remark_english',
            field=models.TextField(blank=True, null=True),
        ),
    ]
