# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-31 13:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0184_auto_20171106_1203'),
    ]

    operations = [
        migrations.RunSQL(
            [(
             "INSERT INTO osis_common_messagetemplate (reference, subject, template, format, language) VALUES (%s, %s, %s, %s, %s);",
             ['learning_unit_year_deletion_html',
              'Suppression de l\u0027unité d\u0027enseignement {learning_unit_acronym}',
              '{% autoescape off %}\r\n<p>Bonjour {{ first_name }} {{ last_name }},<br />\r\nCeci est un message automatique g\u00e9n\u00e9r\u00e9 par le serveur OSIS – Merci de ne pas y r\u00e9pondre.<br />\r\n<br />\r\nVous avez demandé la suppression de l\u0027UE {{ learning_unit_year }} {% if academic_year %}à partir de l\u0027année {{ academic_year }}{% endif %}:<br />\r\n<ul>{% for msg in msg_list%}<li>{{ msg }}</li>{% endfor %}</ul>\r\n<br />\r\nCordialement,<br />\r\nOsis UCLouvain<br /></p>\r\n{% endautoescape %}',
              'HTML',
              'fr-be'])],
        ),
        migrations.RunSQL(
            [(
             "INSERT INTO osis_common_messagetemplate (reference, subject, template, format, language) VALUES (%s, %s, %s, %s, %s);",
             ['learning_unit_year_deletion_txt',
              'Suppression de l\u0027unité d\u0027enseignement {learning_unit_acronym}',
              '<p>Bonjour {{ first_name }} {{ last_name }},<br />\r\nCeci est un message automatique g\u00e9n\u00e9r\u00e9 par le serveur OSIS – Merci de ne pas y r\u00e9pondre.<br />\r\n<br />\r\nVous avez demandé la suppression de l\u0027UE {{ learning_unit_year }} {% if academic_year %}à partir de l\u0027année {{ academic_year }}{% endif %}:<br />\r\n<ul>{% for msg in msg_list%}<li>{{ msg }}</li>{% endfor %}</ul>\r\n<br />\r\nCordialement,<br />\r\nOsis UCLouvain<br /></p>\r\n',
              'PLAIN',
              'fr-be'])],
        ),
        migrations.RunSQL(
            [(
             "INSERT INTO osis_common_messagetemplate (reference, subject, template, format, language) VALUES (%s, %s, %s, %s, %s);",
             ['learning_unit_year_deletion_html',
              'Deletion of the learning unit {learning_unit_acronym}',
              '{% autoescape off %}\r\n<p>Hello {{ first_name }} {{ last_name }},<br />\r\nThis is an automatic message generated by the OSIS server – Please do not reply to this message.<br />\r\n<br />\r\nYou ask for the deletion of the learning unit {{ learning_unit_year }} {% if academic_year %}starting from the year {{ academic_year }}{% endif %}:<br />\r\n<ul>{% for msg in msg_list%}<li>{{ msg }}</li>{% endfor %}</ul>\r\n<br />\r\nRegards,<br />\r\nOsis UCLouvain<br /></p>\r\n{% endautoescape off %}',
              'HTML',
              'en'])],
        ),
        migrations.RunSQL(
            [(
             "INSERT INTO osis_common_messagetemplate (reference, subject, template, format, language) VALUES (%s, %s, %s, %s, %s);",
             ['learning_unit_year_deletion_txt',
              'Deletion of the learning unit {learning_unit_acronym}',
              '<p>Hello {{ first_name }} {{ last_name }},<br />\r\nThis is an automatic message generated by the OSIS server – Please do not reply to this message.<br />\r\n<br />\r\nYou ask for the deletion of the learning unit {{ learning_unit_year }} {% if academic_year %}starting from the year{{ acadmic_year }}{% endif %}:<br />\r\n<ul>{% for msg in msg_list%}<li>{{ msg }}</li>{% endfor %}</ul>\r\n<br />\r\nRegards,<br />\r\nOsis UCLouvain<br /></p>\r\n',
              'PLAIN',
              'en'])],
        ),
    ]
