# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-24 14:01
from __future__ import unicode_literals

from django.db import migrations, connection


def update_program_managers_with_education_group(apps, schema_editor):
    program_manager_education_group_list = _get_program_manager_education_group_list()

    if program_manager_education_group_list:
        for row in program_manager_education_group_list:
            program_manager_id = row.get('program_manager_id')
            education_group_id = row.get('education_group_id')
            _update_manager(program_manager_id, education_group_id)


def _get_program_manager_education_group_list():
    with connection.cursor() as cursor:
        sql = """
            SELECT base_programmanager.id as program_manager_id, base_educationgroup.id as education_group_id
            FROM base_programmanager
            JOIN base_offeryear on (base_offeryear.id = base_programmanager.offer_year_id)
            JOIN base_academicyear on (base_academicyear.id = base_offeryear.academic_year_id)
            JOIN base_educationgroupyear on (base_educationgroupyear.acronym = base_offeryear.acronym)
            JOIN base_educationgroup on (base_educationgroup.id = base_educationgroupyear.education_group_id)
            WHERE base_academicyear.year=2016;"""
        cursor.execute(sql)
        return dictfetchall(cursor)
    return None


def _update_manager(program_manager_id, education_group_id):
    with connection.cursor() as cursor:
        sql = "UPDATE base_programmanager set education_group_id= %s where id= %s"
        cursor.execute(sql, [education_group_id, program_manager_id])


def dictfetchall(cursor):
    """Returns all rows from a cursor as a dict"""
    desc = cursor.description
    return [dict(zip([col[0] for col in desc], row)) for row in cursor.fetchall()]


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0184_auto_20171106_1203'),
    ]

    operations = [
        migrations.RunPython(update_program_managers_with_education_group),
    ]
