# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-20 14:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0186_message_templates_learning_unit_deletion'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationGroupType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.CharField(choices=[('TRAINING', 'TRAINING'), ('MINI_TRAINING', 'MINI_TRAINING'), ('GROUP', 'GROUP')], default='TRAINING', max_length=25)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterModelOptions(
            name='learningunit',
            options={'permissions': (('can_access_learningunit', 'Can access learning unit'), ('can_edit_learningunit_pedagogy', 'Can edit learning unit pedagogy'), ('can_edit_learningunit_specification', 'Can edit learning unit specification'), ('can_delete_learningunit', 'Can delete learning unit'))},
        ),
        migrations.RemoveField(
            model_name='educationgroupyear',
            name='category',
        ),
        migrations.AlterField(
            model_name='academiccalendar',
            name='reference',
            field=models.CharField(blank=True, choices=[('DELIBERATION', 'DELIBERATION'), ('DISSERTATION_SUBMISSION', 'DISSERTATION_SUBMISSION'), ('EXAM_ENROLLMENTS', 'EXAM_ENROLLMENTS'), ('SCORES_EXAM_DIFFUSION', 'SCORES_EXAM_DIFFUSION'), ('SCORES_EXAM_SUBMISSION', 'SCORES_EXAM_SUBMISSION'), ('TEACHING_CHARGE_APPLICATION', 'TEACHING_CHARGE_APPLICATION'), ('COURSE_ENROLLMENT', 'COURSE_ENROLLMENT')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='educationgroupyear',
            name='education_group_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.EducationGroupType'),
        ),
        migrations.AlterUniqueTogether(
            name='offeryearcalendar',
            unique_together=set([('academic_calendar', 'education_group_year')]),
        ),
    ]
