# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-23 12:21
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0186_message_templates_learning_unit_deletion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposalFolder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, max_length=100, null=True)),
                ('changed', models.DateTimeField(auto_now=True, null=True)),
                ('folder_id', models.IntegerField()),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Entity')),
            ],
        ),
        migrations.CreateModel(
            name='ProposalLearningUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, max_length=100, null=True)),
                ('changed', models.DateTimeField(auto_now=True, null=True)),
                ('type', models.CharField(choices=[('CREATION', 'CREATION'), ('MODIFICATION', 'MODIFICATION'), ('TRANSFORMATION', 'TRANSFORMATION'), ('TRANSFORMATION_AND_MODIFICATION', 'TRANSFORMATION_AND_MODIFICATION'), ('SUPPRESSION', 'SUPPRESSION')], max_length=50)),
                ('state', models.CharField(choices=[('FACULTY', 'FACULTY'), ('CENTRAL', 'CENTRAL'), ('SUSPENDED', 'SUSPENDED'), ('ACCEPTED', 'ACCEPTED'), ('REFUSED', 'REFUSED')], max_length=50)),
                ('initial_data', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.ProposalFolder')),
                ('learning_unit_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.LearningUnitYear')),
            ],
        ),
        migrations.AlterModelOptions(
            name='learningunit',
            options={'permissions': (('can_access_learningunit', 'Can access learning unit'), ('can_edit_learningunit_pedagogy', 'Can edit learning unit pedagogy'), ('can_edit_learningunit_specification', 'Can edit learning unit specification'), ('can_delete_learningunit', 'Can delete learning unit'))},
        ),
        migrations.AlterField(
            model_name='academiccalendar',
            name='reference',
            field=models.CharField(blank=True, choices=[('DELIBERATION', 'DELIBERATION'), ('DISSERTATION_SUBMISSION', 'DISSERTATION_SUBMISSION'), ('EXAM_ENROLLMENTS', 'EXAM_ENROLLMENTS'), ('SCORES_EXAM_DIFFUSION', 'SCORES_EXAM_DIFFUSION'), ('SCORES_EXAM_SUBMISSION', 'SCORES_EXAM_SUBMISSION'), ('TEACHING_CHARGE_APPLICATION', 'TEACHING_CHARGE_APPLICATION'), ('COURSE_ENROLLMENT', 'COURSE_ENROLLMENT')], max_length=50, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='offeryearcalendar',
            unique_together=set([('academic_calendar', 'education_group_year')]),
        ),
    ]
