# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-21 08:56
from __future__ import unicode_literals

import base.models.enums.sessions_derogation
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0187_auto_20171120_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupelementyear',
            name='contextual_comment',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='groupelementyear',
            name='current_order',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groupelementyear',
            name='is_mandatory',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='groupelementyear',
            name='max_credits',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='groupelementyear',
            name='min_credits',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='groupelementyear',
            name='relative_credits',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='learningunityear',
            name='contextual_comment',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='learningunityear',
            name='current_order',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='learningunityear',
            name='is_mandatory',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='learningunityear',
            name='relative_credits',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='learningunityear',
            name='sessions_derogation',
            field=models.CharField(choices=[('SESSION_1', 'SESSION_1'), ('SESSION_2', 'SESSION_2'), ('SESSION_3', 'SESSION_3'), ('SESSION_1_2', 'SESSION_1_2'), ('SESSION_1_3', 'SESSION_1_3'), ('SESSION_2_3', 'SESSION_2_3'), ('SESSION_1_2_3', 'SESSION_1_2_3'), ('SESSION_UNDEFINED', 'SESSION_UNDEFINED'), ('SESSION_PARTIAL_2_3','SESSION_PARTIAL_2_3')], default=base.models.enums.sessions_derogation.SessionsDerogationTypes('SESSION_UNDEFINED'), max_length=65),
        ),
    ]
