# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-24 16:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0187_auto_20171123_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposallearningunit',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Person'),
        ),
        migrations.AddField(
            model_name='proposallearningunit',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
