# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-24 08:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0193_auto_20171124_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationgroupyear',
            name='education_group_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='base.EducationGroupType'),
        )
    ]
