# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-24 09:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0194_auto_20171124_0926'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('with_child', models.BooleanField(default=False)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Entity')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Person')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='personentity',
            unique_together=set([('person', 'entity')]),
        ),
    ]
