# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-30 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0198_auto_20171130_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningunitenrollment',
            name='enrollment_state',
            field=models.CharField(blank=True, choices=[('ENROLLED', 'ENROLLED')], max_length=20, null=True),
        ),
    ]
