# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-01 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0199_learningunitenrollment_enrollment_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='examenrollment',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
