# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-06 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0200_examenrollment_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerenrollment',
            name='enrollment_state',
            field=models.CharField(blank=True, choices=[('SUBSCRIBED', 'SUBSCRIBED'), ('PROVISORY', 'PROVISORY'), ('PENDING', 'PENDING'), ('TERMINATION', 'TERMINATION'), ('END_OF_CYCLE', 'END_OF_CYCLE')], max_length=15, null=True),
        ),
    ]
