# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-15 15:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0201_auto_20171204_1659'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'permissions': (('is_administrator', 'Is administrator'), ('is_institution_administrator', 'Is institution administrator '), ('can_edit_administrative_data', 'Can edit administrative data'))},
        ),
    ]
