# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-15 14:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0201_auto_20171204_1659'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offeryearcalendar',
            options={'permissions': (('can_edit_offer_year_calendar', 'Can edit offer year calendar'),)},
        ),
    ]
