# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-27 13:23
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0203_populate_uuid_entity'),
    ]

    operations = [
        migrations.AddField(
            model_name='entityversion',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, null=True),
        ),
    ]
