# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-27 14:47
from __future__ import unicode_literals

import uuid

from django.db import migrations
from base.migrations.utils import utils


def set_uuid_field(apps, schema_editor):
    utils.set_uuids_model(apps, "entityversion")


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0204_auto_20171127_1423'),
    ]

    operations = [
        migrations.RunPython(set_uuid_field),
    ]
