# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-11 13:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0212_remove_offeryearcalendar_customized'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionexamcalendar',
            name='academic_calendar',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.AcademicCalendar'),
        ),
        migrations.AlterUniqueTogether(
            name='sessionexamcalendar',
            unique_together=set([]),
        ),
    ]
