# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-09 14:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0212_remove_offeryearcalendar_customized'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learningcontainer',
            name='auto_renewal_until',
        ),
        migrations.RemoveField(
            model_name='learningcontainer',
            name='start_year',
        ),
    ]
