# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-15 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0214_auto_20180109_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupelementyear',
            name='comment',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='groupelementyear',
            name='comment_english',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='groupelementyear',
            name='minor_access',
            field=models.BooleanField(default=False),
        ),
    ]
