# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-23 14:41
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0220_remove_campus_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningunityear',
            name='credits',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
    ]
