# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-25 15:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0222_auto_20180125_1556'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='learningunityear',
            unique_together=set([('learning_unit', 'academic_year', 'deleted')]),
        ),
    ]
