# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-29 12:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0223_auto_20180129_1106'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='entitycomponentyear',
            unique_together=set([('entity_container_year', 'learning_component_year', 'deleted')]),
        ),
        migrations.AlterUniqueTogether(
            name='entitycontaineryear',
            unique_together=set([('entity', 'learning_container_year', 'type', 'deleted')]),
        ),
        migrations.AlterUniqueTogether(
            name='learningcontaineryear',
            unique_together=set([('learning_container', 'academic_year', 'deleted')]),
        ),
    ]
