# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-29 13:13
from __future__ import unicode_literals

from django.db import migrations

# WARNING !!!! This file is very important to ensure the consistancy !
# Don't FORGET to use it if you merge migration file


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0224_auto_20180129_1308'),
    ]

    operations = [
        migrations.RunSQL(
            """CREATE UNIQUE INDEX learningcontaineryear_learningcontainerid_academicyearid_deleted
                    ON base_learningcontaineryear
                (learning_container_id, academic_year_id, coalesce(deleted,'2000-01-01'));""",
            "DROP INDEX learningcontaineryear_learningcontainerid_academicyearid_deleted"
        ),
        migrations.RunSQL(
            """CREATE UNIQUE INDEX learningunityear_learningunitid_academicyearid_deleted
                    ON base_learningunityear
                (learning_unit_id, academic_year_id, coalesce(deleted,'2000-01-01'));""",
            "DROP INDEX learningunityear_learningunitid_academicyearid_deleted"
        ),
        migrations.RunSQL(
            """CREATE UNIQUE INDEX entitycontaineryear_entityid_learningcontaineryearid_type_deleted
                    ON base_entitycontaineryear
                (entity_id, learning_container_year_id,type, coalesce(deleted,'2000-01-01'));""",
            "DROP INDEX entitycontaineryear_entityid_learningcontaineryearid_type_deleted"
        ),
        migrations.RunSQL(
            """CREATE UNIQUE INDEX entitycomponentyear_entitycontaineryear_learningcomponentyearid_deleted
                    ON base_entitycomponentyear
                (entity_container_year_id, learning_component_year_id, coalesce(deleted,'2000-01-01'));""",
            "DROP INDEX entitycomponentyear_entitycontaineryear_learningcomponentyearid_deleted"
        ),
    ]
