# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-02 10:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0226_auto_20180202_1044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entitycomponentyear',
            name='hourly_volume_partial',
        ),
    ]
