# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-02 08:17
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0227_auto_20180202_1545'),
    ]

    operations = [
        migrations.RenameField(
            model_name='learningcontaineryear',
            old_name='title',
            new_name='common_title',
        ),
        migrations.RenameField(
            model_name='learningcontaineryear',
            old_name='title_english',
            new_name='common_title_english',
        ),
        migrations.RenameField(
            model_name='learningunityear',
            old_name='title_english',
            new_name='specific_title_english',
        ),
        migrations.RenameField(
            model_name='learningunityear',
            old_name='title',
            new_name='specific_title',
        ),
    ]
