# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-02 08:17
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0228_titles_fields_renaming'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningunityear',
            name='specific_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
