# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-07 08:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0230_auto_20180205_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningunityear',
            name='subtype',
            field=models.CharField(choices=[('FULL', 'FULL'), ('PARTIM', 'PARTIM')], default='', max_length=50),
            preserve_default=False,
        ),
    ]
