# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-22 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0232_auto_20180220_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningcomponentyear',
            name='changed',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='learningunitcomponent',
            name='changed',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
