# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-22 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0232_auto_20180220_1527'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proposallearningunit',
            options={'permissions': (('can_edit_learning_unit_proposal', 'Can edit learning unit proposal'),)},
        ),
        migrations.AlterField(
            model_name='proposallearningunit',
            name='state',
            field=models.CharField(choices=[('FACULTY', 'FACULTY'), ('CENTRAL', 'CENTRAL'), ('SUSPENDED', 'SUSPENDED'), ('ACCEPTED', 'ACCEPTED'), ('REFUSED', 'REFUSED')], max_length=50, verbose_name='state'),
        ),
    ]
