# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-26 07:57
from __future__ import unicode_literals

import base.models.enums.proposal_state
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0234_auto_20180222_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposallearningunit',
            name='state',
            field=models.CharField(choices=[('FACULTY', 'FACULTY'), ('CENTRAL', 'CENTRAL'), ('SUSPENDED', 'SUSPENDED'), ('ACCEPTED', 'ACCEPTED'), ('REFUSED', 'REFUSED')], default=base.models.enums.proposal_state.ProposalState('FACULTY'), max_length=50, verbose_name='state'),
        ),
    ]
