# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-12 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0235_auto_20180226_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningcontaineryear',
            name='common_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
