# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-06 07:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0236_learningunityear_summary_editable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningunityear',
            name='summary_editable',
            field=models.BooleanField(default=True, verbose_name='summary_editable'),
        ),
        migrations.AlterField(
            model_name='proposallearningunit',
            name='learning_unit_year',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.LearningUnitYear'),
        ),
    ]
