# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-07 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0236_learningunityear_summary_editable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningunityear',
            name='summary_editable',
            field=models.BooleanField(default=True, verbose_name='summary_editable'),
        ),
    ]
