# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-12 08:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0236_auto_20180312_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningunityear',
            name='specific_title',
            field=models.CharField(max_length=255),
        ),
    ]
