# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-07 12:38
from __future__ import unicode_literals

from django.db import migrations

from base.migrations.utils.utils import initialize_perms


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0238_auto_20180307_1338'),
    ]

    operations = [
        migrations.RunPython(initialize_perms),
    ]
