# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-16 12:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0238_auto_20180307_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposallearningunit',
            name='learning_unit_year',
        ),
    ]
