# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-16 09:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0239_message_template_proposal_cancel'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntityCalendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, max_length=100, null=True)),
                ('changed', models.DateTimeField(auto_now=True, null=True)),
                ('start_date', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('academic_calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.AcademicCalendar')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Entity')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='entitycalendar',
            unique_together=set([('academic_calendar', 'entity')]),
        ),
    ]
