# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-16 09:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0242_proposallearningunit_learning_unit_year'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='proposalfolder',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='proposalfolder',
            name='entity',
        ),
        migrations.RemoveField(
            model_name='proposallearningunit',
            name='folder',
        ),
        migrations.AddField(
            model_name='proposallearningunit',
            name='entity',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='base.Entity'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proposallearningunit',
            name='folder_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='proposallearningunit',
            name='learning_unit_year',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.LearningUnitYear'),
        ),
        migrations.DeleteModel(
            name='ProposalFolder',
        ),
    ]
