# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-16 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0243_auto_20180316_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposallearningunit',
            name='folder_id',
            field=models.PositiveIntegerField(),
        ),
    ]
