# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-21 10:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0244_auto_20180316_1908'),
        ('reference', '0017_auto_20180321_1107')
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campus',
            options={'verbose_name_plural': 'campuses'},
        ),
        migrations.AlterField(
            model_name='campus',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='learningcontaineryear',
            name='language',
            field=models.ForeignKey(blank=True, default='FR', null=True, on_delete=django.db.models.deletion.CASCADE, to='reference.Language'),
        ),
    ]
