# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-26 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0245_auto_20180321_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningunityear',
            name='mobility_modality',
            field=models.TextField(blank=True, null=True, verbose_name='Modalities specific to IN and OUT mobility'),
        ),
    ]
