# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-26 08:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0245_auto_20180321_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposallearningunit',
            name='state',
            field=models.CharField(choices=[('FACULTY', 'FACULTY'), ('CENTRAL', 'CENTRAL'), ('SUSPENDED', 'SUSPENDED'), ('ACCEPTED', 'ACCEPTED'), ('REFUSED', 'REFUSED')], default='FACULTY', max_length=50, verbose_name='state'),
        ),
    ]
