# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-21 15:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0245_auto_20180321_1107'),
    ]

    operations = [
        migrations.RunSQL(
            """
            ALTER TABLE public.base_learningcontaineryear
            ALTER COLUMN language_id TYPE integer USING (trim(language_id)::integer);"""
        )
     ]
