# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-28 07:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0246_auto_20180326_1031'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bibliography',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('mandatory', models.BooleanField(verbose_name='mandatory')),
            ],
            options={
                'verbose_name_plural': 'bibliographies',
            },
        ),
        migrations.RemoveField(
            model_name='learningunityear',
            name='summary_editable',
        ),
        migrations.AddField(
            model_name='learningunityear',
            name='mobility_modality',
            field=models.CharField(blank=True, max_length=250, null=True,
                                   verbose_name='Modalities specific to IN and OUT mobility'),
        ),
        migrations.AddField(
            model_name='learningunityear',
            name='summary_locked',
            field=models.BooleanField(default=False, verbose_name='summary_locked'),
        ),
        migrations.AddField(
            model_name='bibliography',
            name='learning_unit_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.LearningUnitYear'),
        ),
    ]
