# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-27 09:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0247_bibliography'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bibliography',
            options={'verbose_name_plural': 'bibliographies'},
        ),
    ]
