# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-28 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0247_auto_20180328_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningunityear',
            name='mobility_modality',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Modalities specific to IN and OUT mobility'),
        ),
    ]
