# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-27 12:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0248_auto_20180327_1140'),
        ('base', '0246_auto_20180326_1031'),
    ]

    operations = [
    ]
