# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-27 12:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0248_auto_20180328_1347'),
        ('attribution', '0031_auto_20180327_1458'),
    ]

    operations = [
        # Remove all deleted records physically
        migrations.RunSQL("DELETE FROM base_learningunitcomponent CASCADE WHERE deleted is not null"),
        migrations.RunSQL("DELETE FROM base_learningclassyear CASCADE WHERE deleted is not null"),
        migrations.RunSQL("DELETE FROM base_entitycomponentyear CASCADE WHERE deleted is not null"),
        migrations.RunSQL("DELETE FROM base_entitycontaineryear CASCADE WHERE deleted is not null"),
        migrations.RunSQL("DELETE FROM base_learningcomponentyear CASCADE WHERE deleted is not null"),
        migrations.RunSQL("DELETE FROM base_learningunityear CASCADE WHERE deleted is not null"),
        migrations.RunSQL("DELETE FROM base_learningunit CASCADE WHERE deleted is not null"),
        migrations.RunSQL("DELETE FROM base_learningcontaineryear CASCADE WHERE deleted is not null"),
        migrations.RunSQL("DELETE FROM base_learningcontainer CASCADE WHERE deleted is not null"),
        # Remove constraint unique index SQL
        migrations.RunSQL("DROP INDEX IF EXISTS learningcontaineryear_learningcontainerid_academicyearid_deleted"),
        migrations.RunSQL("DROP INDEX IF EXISTS learningunityear_learningunitid_academicyearid_deleted"),
        migrations.RunSQL("DROP INDEX IF EXISTS entitycontaineryear_entityid_learningcontaineryearid_type_deleted"),
        migrations.RunSQL("DROP INDEX IF EXISTS entitycomponentyear_entitycontaineryear_learningcomponentyearid_deleted")
    ]
