# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-30 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0250_auto_20180327_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposallearningunit',
            name='type',
            field=models.CharField(choices=[('CREATION', 'CREATION'), ('MODIFICATION', 'MODIFICATION'), ('TRANSFORMATION', 'TRANSFORMATION'), ('TRANSFORMATION_AND_MODIFICATION', 'TRANSFORMATION_AND_MODIFICATION'), ('SUPPRESSION', 'SUPPRESSION')], default='MODIFICATION', max_length=50, verbose_name='type'),
        ),
    ]
