# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-09 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0251_auto_20180404_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningunit',
            name='periodicity',
            field=models.CharField(choices=[('ANNUAL', 'ANNUAL'), ('BIENNIAL_EVEN', 'BIENNIAL_EVEN'), ('BIENNIAL_ODD', 'BIENNIAL_ODD')], default='ANNUAL', max_length=20, verbose_name='periodicity'),
        ),
    ]
