# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-12 07:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0253_message_template_proposal_consolidate'),
        ('base', '0252_auto_20180409_1209'),
    ]

    operations = [
    ]
