# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-16 06:17
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0253_message_template_proposal_consolidate'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningAchievements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False)),
                ('code_name', models.CharField(max_length=100, verbose_name='code')),
                ('text', ckeditor.fields.RichTextField(null=True, verbose_name='text')),
                ('learning_unit_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.LearningUnitYear')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='learningachievements',
            unique_together=set([('code_name', 'learning_unit_year')]),
        ),
    ]
