# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-31 13:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0253_message_template_proposal_consolidate'),
    ]

    operations = [
        migrations.RunSQL(
            [(
             "INSERT INTO osis_common_messagetemplate (reference, subject, template, format, language) VALUES (%s, %s, %s, %s, %s);",
             ['learning_unit_proposal_consolidated_html',
              'Rapport consolidation des mises en proposition',
              '{% autoescape off %}\r\n<p>Bonjour {{ first_name }} {{ last_name }},</p>\r\n<p>Ceci est un message automatique g\u00e9n\u00e9r\u00e9 par le serveur OSIS – Merci de ne pas y r\u00e9pondre.</p>\r\n<p>Vous avez demandé la consolidation des mises en proposition suivantes:</p>\r\n<p>{{ proposals }}</p>\r\n<p>Cordialement,\r\nOsis UCLouvain</p>\r\n{% endautoescape %}',
              'HTML',
              'fr-be'])],
        ),
        migrations.RunSQL(
            [(
             "INSERT INTO osis_common_messagetemplate (reference, subject, template, format, language) VALUES (%s, %s, %s, %s, %s);",
             ['learning_unit_proposal_consolidated_txt',
              'Rapport consolidation des mises en proposition',
              '<p>Bonjour {{ first_name }} {{ last_name }},</p>\r\n<p>Ceci est un message automatique g\u00e9n\u00e9r\u00e9 par le serveur OSIS – Merci de ne pas y r\u00e9pondre.</p>\r\n<p>Vous avez demandé la consolidation des mises en proposition suivantes :</p>\r\n<p>{{ proposals }}</p>\r\n<p>Cordialement,\r\nOsis UCLouvain</p>\r\n',
              'PLAIN',
              'fr-be'])],
        ),
        migrations.RunSQL(
            [(
             "INSERT INTO osis_common_messagetemplate (reference, subject, template, format, language) VALUES (%s, %s, %s, %s, %s);",
             ['learning_unit_proposal_consolidated_html',
              'Report consolidation of the proposals',
              '{% autoescape off %}\r\n<p>Hello {{ first_name }} {{ last_name }},</p>\r\n<p>This is an automatic message generated by the OSIS server – Please do not reply to this message.</p>\r\n<p>You asked for the consolidation of the proposals below :</p>\r\n<p>{{ proposals }}</p>\r\n<p>Regards,\r\nOsis UCLouvain</p>\r\n{% endautoescape off %}',
              'HTML',
              'en'])],
        ),
        migrations.RunSQL(
            [(
             "INSERT INTO osis_common_messagetemplate (reference, subject, template, format, language) VALUES (%s, %s, %s, %s, %s);",
             ['learning_unit_proposal_consolidated_txt',
              'Report consolidation of the proposals',
              '<p>Hello {{ first_name }} {{ last_name }},</p>\r\n<p>This is an automatic message generated by the OSIS server – Please do not reply to this message.</p>\r\n<p>You asked for the consolidation of the proposals below  :</p>\r\n<p>{{ proposals }}</p>\r\n<p>Regards,\r\nOsis UCLouvain</p>\r\n',
              'PLAIN',
              'en'])],
        ),
    ]