# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-16 07:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0017_language_changed'),
        ('base', '0254_auto_20180416_0817'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningachievements',
            name='language',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='reference.Language'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='learningachievements',
            unique_together=set([('code_name', 'learning_unit_year', 'language')]),
        ),
    ]
