# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-31 13:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0254_message_template_action_proposal'),
    ]

    operations = [
        migrations.RunSQL(
            [(
             "INSERT INTO osis_common_messagetemplate (reference, subject, template, format, language) VALUES (%s, %s, %s, %s, %s);",
             ['learning_unit_proposal_canceled_html',
              'Rapport annulation des mises en proposition',
              "{% autoescape off %}<p>Ceci est un message automatique g\u00e9n\u00e9r\u00e9 par le serveur OSIS – Merci de ne pas y r\u00e9pondre.</p>\r\n<p>Vous avez demandé l'annulation des mises en proposition suivantes:</p>\r\n<p>{{ proposals }}</p>\r\n<p>Cordialement,\r\nOsis UCLouvain</p>\r\n{% endautoescape%}",
              'HTML',
              'fr-be'])],
        ),
        migrations.RunSQL(
            [(
             "INSERT INTO osis_common_messagetemplate (reference, subject, template, format, language) VALUES (%s, %s, %s, %s, %s);",
             ['learning_unit_proposal_canceled_txt',
              'Rapport annulation des mises en proposition',
              "<p>Ceci est un message automatique g\u00e9n\u00e9r\u00e9 par le serveur OSIS – Merci de ne pas y r\u00e9pondre.</p>\r\n<p>Vous avez demandé l'annulation des mises en proposition suivantes :</p>\r\n<p>{{ proposals }}</p>\r\n<p>Cordialement,\r\nOsis UCLouvain</p>\r\n",
              'PLAIN',
              'fr-be'])],
        ),
        migrations.RunSQL(
            [(
             "INSERT INTO osis_common_messagetemplate (reference, subject, template, format, language) VALUES (%s, %s, %s, %s, %s);",
             ['learning_unit_proposal_canceled_html',
              'Report cancellation of the proposals',
              '{% autoescape off %}<p>This is an automatic message generated by the OSIS server – Please do not reply to this message.</p>\r\n<p>You asked for the cancellation of the proposals below :</p>\r\n<p>{{ proposals }}</p>\r\n<p>Regards,\r\nOsis UCLouvain</p>\r\n{% endautoescape%}',
              'HTML',
              'en'])],
        ),
        migrations.RunSQL(
            [(
             "INSERT INTO osis_common_messagetemplate (reference, subject, template, format, language) VALUES (%s, %s, %s, %s, %s);",
             ['learning_unit_proposal_canceled_txt',
              'Report cancellation of the proposals',
              '<p>This is an automatic message generated by the OSIS server – Please do not reply to this message.</p>\r\n<p>You asked for the cancellation of the proposals below  :</p>\r\n<p>{{ proposals }}</p>\r\n<p>Regards,\r\nOsis UCLouvain</p>\r\n',
              'PLAIN',
              'en'])],
        ),
    ]