# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-16 10:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0256_auto_20180416_1024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupelementyear',
            name='absolute_credits',
        ),
    ]
