# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-16 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0257_remove_groupelementyear_absolute_credits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningcontaineryear',
            name='container_type',
            field=models.CharField(choices=[('COURSE', 'COURSE'), ('INTERNSHIP', 'INTERNSHIP'), ('DISSERTATION', 'DISSERTATION'), ('OTHER_COLLECTIVE', 'OTHER_COLLECTIVE'), ('OTHER_INDIVIDUAL', 'OTHER_INDIVIDUAL'), ('MASTER_THESIS', 'MASTER_THESIS'), ('EXTERNAL', 'EXTERNAL')], max_length=20),
        ),
    ]
