# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-16 12:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0258_auto_20180416_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningcontaineryear',
            name='campus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Campus'),
        ),
        migrations.AlterField(
            model_name='learningcontaineryear',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reference.Language'),
        ),
    ]
