# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-16 11:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0254_merge_20180412_0952'),
        ('base', '0258_auto_20180416_1300'),
    ]

    operations = [
    ]
