# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-16 12:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0259_auto_20180416_1404'),
        ('base', '0259_merge_20180416_1325'),
    ]

    operations = [
    ]
