# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-16 16:39
from __future__ import unicode_literals

import base.models.learning_unit_year
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0259_auto_20180416_1404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learningunit',
            name='acronym',
        ),
        migrations.RemoveField(
            model_name='learningunit',
            name='title',
        ),
        migrations.AlterField(
            model_name='learningcontaineryear',
            name='common_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='common_official_title'),
        ),
        migrations.AlterField(
            model_name='learningcontaineryear',
            name='common_title_english',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='common_official_english_title'),
        ),
        migrations.AlterField(
            model_name='learningcontaineryear',
            name='container_type',
            field=models.CharField(choices=[('COURSE', 'COURSE'), ('INTERNSHIP', 'INTERNSHIP'), ('DISSERTATION', 'DISSERTATION'), ('OTHER_COLLECTIVE', 'OTHER_COLLECTIVE'), ('OTHER_INDIVIDUAL', 'OTHER_INDIVIDUAL'), ('MASTER_THESIS', 'MASTER_THESIS'), ('EXTERNAL', 'EXTERNAL')], max_length=20, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='learningcontaineryear',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reference.Language', verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='learningunit',
            name='faculty_remark',
            field=models.TextField(blank=True, null=True, verbose_name='faculty_remark'),
        ),
        migrations.AlterField(
            model_name='learningunit',
            name='other_remark',
            field=models.TextField(blank=True, null=True, verbose_name='other_remark'),
        ),
        migrations.AlterField(
            model_name='learningunit',
            name='periodicity',
            field=models.CharField(choices=[('ANNUAL', 'ANNUAL'), ('BIENNIAL_EVEN', 'BIENNIAL_EVEN'), ('BIENNIAL_ODD', 'BIENNIAL_ODD')], default='ANNUAL', max_length=20, verbose_name='periodicity'),
        ),
        migrations.AlterField(
            model_name='learningunityear',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.AcademicYear', validators=[base.models.learning_unit_year.academic_year_validator], verbose_name='academic_year'),
        ),
        migrations.AlterField(
            model_name='learningunityear',
            name='acronym',
            field=models.CharField(db_index=True, max_length=15, validators=[django.core.validators.RegexValidator('^[BLMW][A-Z]{2,4}\\d{4}[A-Z0-9]{0,1}$')], verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='learningunityear',
            name='internship_subtype',
            field=models.CharField(blank=True, choices=[('TEACHING_INTERNSHIP', 'TEACHING_INTERNSHIP'), ('CLINICAL_INTERNSHIP', 'CLINICAL_INTERNSHIP'), ('PROFESSIONAL_INTERNSHIP', 'PROFESSIONAL_INTERNSHIP'), ('RESEARCH_INTERNSHIP', 'RESEARCH_INTERNSHIP')], max_length=250, null=True, verbose_name='internship_subtype'),
        ),
        migrations.AlterField(
            model_name='learningunityear',
            name='quadrimester',
            field=models.CharField(blank=True, choices=[('Q1', 'Q1'), ('Q2', 'Q2'), ('Q1&2', 'Q1&2'), ('Q1|2', 'Q1|2'), ('Q3', 'Q3')], max_length=4, null=True, verbose_name='quadrimester'),
        ),
        migrations.AlterField(
            model_name='learningunityear',
            name='specific_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='official_title_proper_to_UE'),
        ),
        migrations.AlterField(
            model_name='learningunityear',
            name='specific_title_english',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='official_english_title_proper_to_UE'),
        ),
        migrations.AlterField(
            model_name='learningunityear',
            name='status',
            field=models.BooleanField(default=False, verbose_name='active_title'),
        ),
        migrations.AlterField(
            model_name='learningunityear',
            name='subtype',
            field=models.CharField(choices=[('FULL', 'FULL'), ('PARTIM', 'PARTIM')], default='FULL', max_length=50),
        ),
    ]
