# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-18 08:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0260_auto_20180416_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerenrollment',
            name='education_group_year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.EducationGroupYear'),
        ),
    ]
