# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-31 13:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0261_offerenrollment_education_group_year'),
    ]

    operations = [
        migrations.RunSQL(
            [("UPDATE osis_common_messagetemplate  SET template=%s WHERE reference=%s AND language=%s;",
             ['{% autoescape off %}\r\n<p>Bonjour {{ first_name }} {{ last_name }},</p>\r\n<p>Ceci est un message automatique g\u00e9n\u00e9r\u00e9 par le serveur OSIS – Merci de ne pas y r\u00e9pondre.</p>\r\n<p>Vous avez demandé la consolidation de mises en proposition. Vous trouverez ci-joint le rapport détaillé.</p><p>\r\nCordialement,\r\nOsis UCLouvain</p>\r\n{% endautoescape %}',
              'learning_unit_proposal_consolidated_html',
              'fr-be'])],
        ),
        migrations.RunSQL(
            [(
             "UPDATE osis_common_messagetemplate  SET template=%s WHERE reference=%s AND language=%s;",
             ['<p>Bonjour {{ first_name }} {{ last_name }},</p>\r\n<p>Ceci est un message automatique g\u00e9n\u00e9r\u00e9 par le serveur OSIS – Merci de ne pas y r\u00e9pondre.</p>\r\n<p>Vous avez demandé la consolidation de mises en proposition. Vous trouverez ci-joint le rapport détaillé.</p><p>\r\nCordialement,\r\nOsis UCLouvain</p>\r\n',
              'learning_unit_proposal_consolidated_txt',
              'fr-be'])],
        ),
        migrations.RunSQL(
            [(
             "UPDATE osis_common_messagetemplate  SET template=%s WHERE reference=%s AND language=%s;",
             ['{% autoescape off %}\r\n<p>Hello {{ first_name }} {{ last_name }},</p>\r\n<p>This is an automatic message generated by the OSIS server – Please do not reply to this message.</p>\r\n<p>You have requested consolidation of proposals. You will find attached the detailed report.</p><p>\r\nRegards,\r\nOsis UCLouvain</p>\r\n{% endautoescape off %}',
              'learning_unit_proposal_consolidated_html',
              'en'])],
        ),
        migrations.RunSQL(
            [(
             "UPDATE osis_common_messagetemplate  SET template=%s WHERE reference=%s AND language=%s;",
             ['<p>Hello {{ first_name }} {{ last_name }},</p>\r\n<p>This is an automatic message generated by the OSIS server – Please do not reply to this message.</p>\r\n<p>You have requested consolidation of proposals. You will find attached the detailed report.</p><p>\r\nRegards,\r\nOsis UCLouvain</p>\r\n',
              'learning_unit_proposal_consolidated_txt',
              'en'])],
        ),
        migrations.RunSQL(
            [(
                "UPDATE osis_common_messagetemplate  SET template=%s WHERE reference=%s AND language=%s;",
                ['{% autoescape off %}\r\n<p>Bonjour {{ first_name }} {{ last_name }},</p>\r\n<p>Ceci est un message automatique g\u00e9n\u00e9r\u00e9 par le serveur OSIS – Merci de ne pas y r\u00e9pondre.</p>\r\n<p>Vous avez demandé l\u0027annulation de mises en proposition. Vous trouverez ci-joint le rapport détaillé.</p><p>\r\nCordialement,\r\nOsis UCLouvain</p>\r\n{% endautoescape %}',
                 'learning_unit_proposal_canceled_html',
                 'fr-be'])],
        ),
        migrations.RunSQL(
            [(
                "UPDATE osis_common_messagetemplate  SET template=%s WHERE reference=%s AND language=%s;",
                ['<p>Bonjour {{ first_name }} {{ last_name }},</p>\r\n<p>Ceci est un message automatique g\u00e9n\u00e9r\u00e9 par le serveur OSIS – Merci de ne pas y r\u00e9pondre.</p>\r\n<p>Vous avez demandé l\u0027annulation de mises en proposition. Vous trouverez ci-joint le rapport détaillé.</p><p>\r\nCordialement,\r\nOsis UCLouvain</p>\r\n',
                 'learning_unit_proposal_canceled_txt',
                 'fr-be'])],
        ),
        migrations.RunSQL(
            [(
                "UPDATE osis_common_messagetemplate  SET template=%s WHERE reference=%s AND language=%s;",
                ['{% autoescape off %}\r\n<p>Hello {{ first_name }} {{ last_name }},</p>\r\n<p>This is an automatic message generated by the OSIS server – Please do not reply to this message.</p>\r\n<p>You have requested cancellation of proposals. You will find attached the detailed report.</p><p>\r\nRegards,\r\nOsis UCLouvain</p>\r\n{% endautoescape off %}',
                 'learning_unit_proposal_canceled_html',
                 'en'])],
        ),
        migrations.RunSQL(
            [(
                "UPDATE osis_common_messagetemplate  SET template=%s WHERE reference=%s AND language=%s;",
                ['<p>Hello {{ first_name }} {{ last_name }},</p>\r\n<p>This is an automatic message generated by the OSIS server – Please do not reply to this message.</p>\r\n<p>You have requested cancellation of proposals. You will find attached the detailed report.</p><p>\r\nRegards,\r\nOsis UCLouvain</p>\r\n',
                 'learning_unit_proposal_canceled_txt',
                 'en'])]
        )
    ]