# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-20 08:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0263_fix_message_consolidation_cancellation_proposals'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LearningAchievements',
            new_name='LearningAchievement',
        ),
    ]
