# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-03 07:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0266_auto_20180425_1611'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='educationgroup',
            options={'permissions': (('can_access_education_group', 'Can access education_group'), ('can_edit_educationgroup_pedagogy', 'Can edit education group pedagogy'))},
        ),
    ]
