# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-31 13:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0268_learningcomponentyear_cm_to_pm'),
    ]

    operations = [
        migrations.RunSQL(
            [("UPDATE base_learningcomponentyear SET acronym = replace(acronym, 'TP', 'PP')"), ]
        )
    ]