# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-25 09:53
from __future__ import unicode_literals

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0272_auto_20180524_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='externallearningunityear',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Person'),
        ),
        migrations.AddField(
            model_name='externallearningunityear',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='externallearningunityear',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Entity', verbose_name='requesting_entity'),
        ),
        migrations.AlterField(
            model_name='externallearningunityear',
            name='external_credits',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(500)], verbose_name='local_credits'),
        ),
        migrations.AlterField(
            model_name='learningunityear',
            name='acronym',
            field=models.CharField(db_index=True, max_length=15, validators=[django.core.validators.RegexValidator('^[BLMWX][A-Z]{2,4}\\d{4}[A-Z0-9]{0,1}$')], verbose_name='code'),
        ),
    ]
