# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-28 11:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0273_auto_20180525_1153'),
    ]

    operations = [
        migrations.RenameField(
            model_name='externallearningunityear',
            old_name='buyer',
            new_name='requesting_entity',
        ),
    ]
