# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-29 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0274_auto_20180528_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externallearningunityear',
            name='external_acronym',
            field=models.CharField(blank=True, db_index=True, max_length=15, null=True, verbose_name='external_code'),
        ),
    ]
