# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-29 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0274_auto_20180528_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningcontaineryear',
            name='common_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='common_title'),
        ),
        migrations.AlterField(
            model_name='learningcontaineryear',
            name='common_title_english',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='common_english_title'),
        ),
        migrations.AlterField(
            model_name='learningunityear',
            name='specific_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='title_proper_to_UE'),
        ),
        migrations.AlterField(
            model_name='learningunityear',
            name='specific_title_english',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='english_title_proper_to_UE'),
        ),
    ]
