# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-29 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0275_auto_20180529_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningunityear',
            name='professional_integration',
            field=models.BooleanField(default=False, verbose_name='professional_integration'),
        )
    ]
