# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-01 09:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0276_auto_20180530_1552'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='externallearningunityear',
            options={'permissions': (('can_access_externallearningunityear', 'Can access external learning unit'),)},
        ),
    ]
