# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-01 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0277_auto_20180601_1458'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='externallearningunityear',
            options={'permissions': (('can_access_externallearningunityear', 'Can access external learning unit year'),)},
        ),
        migrations.AlterField(
            model_name='learningcontaineryear',
            name='common_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='common_title'),
        ),
        migrations.AlterField(
            model_name='learningcontaineryear',
            name='common_title_english',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='common_english_title'),
        ),
        migrations.AlterField(
            model_name='learningunityear',
            name='specific_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='title_proper_to_UE'),
        ),
        migrations.AlterField(
            model_name='learningunityear',
            name='specific_title_english',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='english_title_proper_to_UE'),
        ),
    ]
