# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-04 12:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0278_auto_20180601_1600'),
    ]

    operations = [
        migrations.RenameField(
            model_name='learningcomponentyear',
            old_name='hourly_volume_partial',
            new_name='hourly_volume_partial_q1',
        ),
        migrations.AddField(
            model_name='learningcomponentyear',
            name='hourly_volume_partial_q2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='learningcomponentyear',
            name='hourly_volume_total_annual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
