# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-06 08:04
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0278_auto_20180601_1600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learningcontaineryear',
            name='campus',
        ),
        migrations.AddField(
            model_name='learningunityear',
            name='campus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Campus'),
        ),
    ]
