# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-04 11:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0017_language_changed'),
        ('base', '0278_auto_20180601_1600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learningcontaineryear',
            name='language',
        ),
        migrations.AddField(
            model_name='learningunityear',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reference.Language', verbose_name='language'),
        ),
    ]
