# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-04 14:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0278_auto_20180601_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningunityear',
            name='learning_container_year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.LearningContainerYear'),
        ),
    ]
