# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-06 07:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0279_auto_20180604_1600'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='learningunityear',
            managers=[
                ('objects_with_container', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='learningunityear',
            name='quadrimester',
            field=models.CharField(blank=True, choices=[('Q1', 'Q1'), ('Q2', 'Q2'), ('Q1 et Q2', 'Q1 et Q2'), ('Q1 ou Q2', 'Q1 ou Q2'), ('Q3', 'Q3')], max_length=4, null=True, verbose_name='quadrimester'),
        ),
    ]
