# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-06 05:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0017_language_changed'),
        ('base', '0279_auto_20180604_1600'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='learningunityear',
            managers=[
                ('objects_with_container', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='learningcontaineryear',
            name='language',
        ),
        migrations.AddField(
            model_name='learningunityear',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reference.Language', verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='learningcontaineryear',
            name='campus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Campus', verbose_name='institution'),
        ),
    ]
