# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-06 08:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0280_auto_20180606_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningcontaineryear',
            name='campus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Campus', verbose_name='institution'),
        ),
    ]
