# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-06 11:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0281_auto_20180604_1441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learningcontaineryear',
            name='campus',
        ),
        migrations.AddField(
            model_name='learningunityear',
            name='campus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Campus'),
        ),
    ]
