# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-07 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0282_auto_20180606_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningunityear',
            name='existing_proposal_in_epc',
            field=models.BooleanField(default=False),
        ),
    ]
