# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-07 15:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0282_auto_20180606_1332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learningcomponentyear',
            name='title',
        ),
    ]
