# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-12 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0284_auto_20180608_1447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learningunit',
            name='periodicity',
        ),
        migrations.AddField(
            model_name='learningunityear',
            name='periodicity',
            field=models.CharField(choices=[('ANNUAL', 'ANNUAL'), ('BIENNIAL_EVEN', 'BIENNIAL_EVEN'), ('BIENNIAL_ODD', 'BIENNIAL_ODD')], default='ANNUAL', max_length=20, verbose_name='periodicity'),
        ),
    ]
