# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-13 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0285_auto_20180612_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningcomponentyear',
            name='planned_classes',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='learningunityear',
            name='quadrimester',
            field=models.CharField(blank=True, choices=[('Q1', 'Q1'), ('Q2', 'Q2'), ('Q1 et Q2', 'Q1 et Q2'), ('Q1 ou Q2', 'Q1 ou Q2'), ('Q3', 'Q3')], max_length=8, null=True, verbose_name='quadrimester'),
        ),
    ]
