# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-15 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0286_auto_20180615_1145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learningunityear',
            name='existing_proposal_in_epc',
        ),
        migrations.AddField(
            model_name='learningunit',
            name='existing_proposal_in_epc',
            field=models.BooleanField(default=False),
        ),
    ]
