# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-15 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0286_auto_20180613_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningcomponentyear',
            name='hourly_volume_partial_q1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='volume horaire partiel q1'),
        ),
        migrations.AlterField(
            model_name='learningcomponentyear',
            name='hourly_volume_partial_q2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='volume horaire partiel q2'),
        ),
        migrations.AlterField(
            model_name='learningcomponentyear',
            name='hourly_volume_total_annual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='volume horaire total annuel'),
        ),
        migrations.AlterField(
            model_name='learningcomponentyear',
            name='volume_declared_vacant',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='volume déclaré vacant'),
        ),
    ]
