# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-19 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0288_auto_20180618_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningcomponentyear',
            name='hourly_volume_partial_q1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='hourly volume partial q1'),
        ),
        migrations.AlterField(
            model_name='learningcomponentyear',
            name='hourly_volume_partial_q2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='hourly volume partial q2'),
        ),
        migrations.AlterField(
            model_name='learningcomponentyear',
            name='hourly_volume_total_annual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='hourly volume total annual'),
        ),
        migrations.AlterField(
            model_name='learningcomponentyear',
            name='volume_declared_vacant',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='volume declared vacant'),
        ),
    ]
