# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-19 07:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0288_auto_20180618_1323'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='educationgroup',
            options={'permissions': (('can_access_education_group', 'Can access education_group'), ('can_edit_educationgroup_pedagogy', 'Can edit education group pedagogy'), ('can_create_education_group', 'Can create education group'))},
        ),
        migrations.AlterField(
            model_name='educationgroupyear',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.AcademicYear', verbose_name='validity'),
        ),
        migrations.AlterField(
            model_name='educationgroupyear',
            name='acronym',
            field=models.CharField(db_index=True, max_length=40, verbose_name='acronym'),
        ),
        migrations.AlterField(
            model_name='educationgroupyear',
            name='credits',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='credits'),
        ),
        migrations.AlterField(
            model_name='educationgroupyear',
            name='education_group_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.EducationGroupType', verbose_name='training_type'),
        ),
        migrations.AlterField(
            model_name='educationgroupyear',
            name='enrollment_campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrollment', to='base.Campus', verbose_name='enrollment_campus'),
        ),
        migrations.AlterField(
            model_name='educationgroupyear',
            name='main_teaching_campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teaching', to='base.Campus', verbose_name='learning_location'),
        ),
        migrations.AlterField(
            model_name='educationgroupyear',
            name='partial_acronym',
            field=models.CharField(db_index=True, max_length=15, null=True, verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='educationgroupyear',
            name='remark',
            field=models.TextField(blank=True, null=True, verbose_name='remark'),
        ),
        migrations.AlterField(
            model_name='educationgroupyear',
            name='remark_english',
            field=models.TextField(blank=True, null=True, verbose_name='remark_english'),
        ),
        migrations.AlterField(
            model_name='educationgroupyear',
            name='title',
            field=models.CharField(max_length=255, verbose_name='title_in_french'),
        ),
        migrations.AlterField(
            model_name='educationgroupyear',
            name='title_english',
            field=models.CharField(blank=True, max_length=240, null=True, verbose_name='title_in_english'),
        ),
    ]
