# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-19 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0290_auto_20180619_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationgroupyear',
            name='max_credits',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='educationgroupyear',
            name='min_credits',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
