# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-21 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0291_auto_20180619_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationgroupyear',
            name='max_credits',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='maximum credits'),
        ),
        migrations.AlterField(
            model_name='educationgroupyear',
            name='min_credits',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='minimum credits'),
        ),
    ]
