# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-21 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0292_auto_20180621_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningunityear',
            name='mobility_modality',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Mobility'),
        ),
    ]
