# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-28 13:52
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0295_auto_20180627_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationgroupyear',
            name='administration_entity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='administration_entity', to='base.Entity', verbose_name='administration_entity'),
        ),
        migrations.AddField(
            model_name='educationgroupyear',
            name='management_entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='management_entity', to='base.Entity', verbose_name='management_entity'),
        ),
    ]
