# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-02 12:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0297_auto_20180629_1443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learningunityear',
            name='bibliography',
        ),
    ]
