# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-02 12:13
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0297_auto_20180629_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationgroup',
            name='end_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='end'),
        ),
        migrations.AlterField(
            model_name='educationgroup',
            name='start_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='start'),
        ),
        migrations.AlterField(
            model_name='educationgrouptype',
            name='category',
            field=models.CharField(choices=[('TRAINING', 'TRAINING'), ('MINI_TRAINING', 'MINI_TRAINING'), ('GROUP', 'GROUP')], default='TRAINING', max_length=25, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='educationgrouptype',
            name='name',
            field=models.CharField(max_length=255, verbose_name='training_type'),
        ),
        migrations.AlterField(
            model_name='educationgroupyear',
            name='academic_type',
            field=models.CharField(blank=True, choices=[('NON_ACADEMIC', 'NON_ACADEMIC'), ('NON_ACADEMIC_CREF', 'NON_ACADEMIC_CREF'), ('ACADEMIC', 'ACADEMIC')], max_length=20, null=True, verbose_name='academic_type'),
        ),
        migrations.AlterField(
            model_name='educationgroupyear',
            name='active',
            field=models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE'), ('RE_REGISTRATION', 'RE_REGISTRATION')], default='ACTIVE', max_length=20, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='educationgroupyear',
            name='admission_exam',
            field=models.BooleanField(default=False, verbose_name='admission_exam'),
        ),
        migrations.AlterField(
            model_name='educationgroupyear',
            name='dissertation',
            field=models.BooleanField(default=False, verbose_name='dissertation'),
        ),
        migrations.AlterField(
            model_name='educationgroupyear',
            name='duration',
            field=models.IntegerField(blank=True, null=True, verbose_name='duration'),
        ),
        migrations.AlterField(
            model_name='educationgroupyear',
            name='duration_unit',
            field=models.CharField(blank=True, choices=[('QUADRIMESTER', 'QUADRIMESTER'), ('TRIMESTER', 'TRIMESTER'), ('MONTH', 'MONTH'), ('WEEK', 'WEEK'), ('DAY', 'DAY')], default='QUADRIMESTER', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='educationgroupyear',
            name='enrollment_enabled',
            field=models.BooleanField(default=False, verbose_name='enrollment_enabled'),
        ),
        migrations.AlterField(
            model_name='educationgroupyear',
            name='funding',
            field=models.BooleanField(default=False, verbose_name='funding'),
        ),
        migrations.AlterField(
            model_name='educationgroupyear',
            name='funding_cud',
            field=models.BooleanField(default=False, verbose_name='funding_cud'),
        ),
        migrations.AlterField(
            model_name='educationgroupyear',
            name='funding_direction',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='funding_direction'),
        ),
        migrations.AlterField(
            model_name='educationgroupyear',
            name='funding_direction_cud',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='cud_funding_direction'),
        ),
        migrations.AlterField(
            model_name='educationgroupyear',
            name='internship',
            field=models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO'), ('OPTIONAL', 'OPTIONAL')], max_length=20, null=True, verbose_name='internship'),
        ),
        migrations.AlterField(
            model_name='educationgroupyear',
            name='keywords',
            field=models.CharField(blank=True, max_length=320, null=True, verbose_name='keywords'),
        ),
        migrations.AlterField(
            model_name='educationgroupyear',
            name='other_campus_activities',
            field=models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO'), ('OPTIONAL', 'OPTIONAL')], max_length=20, null=True, verbose_name='other_campus_activities'),
        ),
        migrations.AlterField(
            model_name='educationgroupyear',
            name='other_language_activities',
            field=models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO'), ('OPTIONAL', 'OPTIONAL')], max_length=20, null=True, verbose_name='other_language_activities'),
        ),
        migrations.AlterField(
            model_name='educationgroupyear',
            name='partial_deliberation',
            field=models.BooleanField(default=False, verbose_name='partial_deliberation'),
        ),
        migrations.AlterField(
            model_name='educationgroupyear',
            name='primary_language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reference.Language', verbose_name='primary_language'),
        ),
        migrations.AlterField(
            model_name='educationgroupyear',
            name='schedule_type',
            field=models.CharField(choices=[('DAILY', 'DAILY'), ('SHIFTED', 'SHIFTED'), ('ADAPTED', 'ADAPTED')], default='DAILY', max_length=20, verbose_name='schedule_type'),
        ),
        migrations.AlterField(
            model_name='educationgroupyear',
            name='university_certificate',
            field=models.BooleanField(default=False, verbose_name='university_certificate'),
        ),
    ]
