# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-02 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0017_language_changed'),
        ('base', '0298_auto_20180702_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationgroupyear',
            name='domains',
            field=models.ManyToManyField(related_name='education_group_years', through='base.OfferYearDomain', to='reference.Domain'),
        ),
    ]
