# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-02 12:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0298_unauthorizedrelationship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unauthorizedrelationship',
            name='child_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unauthorized_child_type', to='base.EducationGroupType'),
        ),
        migrations.AlterField(
            model_name='unauthorizedrelationship',
            name='parent_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unauthorized_parent_type', to='base.EducationGroupType'),
        ),
    ]
