# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-03 12:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0017_language_changed'),
        ('base', '0300_auto_20180703_0941'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationGroupYearDomain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('external_id', models.CharField(blank=True, max_length=100, null=True)),
                ('changed', models.DateTimeField(auto_now=True, null=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reference.Domain')),
                ('education_group_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.EducationGroupYear')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='teachingmaterial',
            options={'ordering': ('learning_unit_year', 'order'), 'verbose_name_plural': 'bibliographies'},
        ),
        migrations.RemoveField(
            model_name='offeryeardomain',
            name='education_group_year',
        ),
        migrations.AddField(
            model_name='educationgroupyear',
            name='domains',
            field=models.ManyToManyField(related_name='education_group_years', through='base.EducationGroupYearDomain', to='reference.Domain'),
        ),
    ]
