# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-05 09:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0302_auto_20180704_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offeryeardomain',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reference.Domain'),
        ),
    ]
