# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-05 08:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0302_auto_20180704_1417'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorizedRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed', models.DateTimeField(auto_now=True)),
                ('child_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorized_child_type', to='base.EducationGroupType')),
                ('parent_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorized_parent_type', to='base.EducationGroupType')),
            ],
        ),
        migrations.RemoveField(
            model_name='unauthorizedrelationship',
            name='child_type',
        ),
        migrations.RemoveField(
            model_name='unauthorizedrelationship',
            name='parent_type',
        ),
        migrations.DeleteModel(
            name='UnauthorizedRelationship',
        ),
    ]
