# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-05 12:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('base', '0299_educationgroupyear_domains'),
        ('base', '0304_auto_20180705_1115'),
    ]

    operations = [
    ]
