# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-05 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0304_auto_20180705_1115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educationgroupyeardomain',
            name='domain',
        ),
        migrations.RemoveField(
            model_name='educationgroupyeardomain',
            name='education_group_year',
        ),
        migrations.AlterField(
            model_name='educationgroupyear',
            name='domains',
            field=models.ManyToManyField(related_name='education_group_years', to='reference.Domain'),
        ),
        migrations.DeleteModel(
            name='EducationGroupYearDomain',
        ),
    ]
