# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-05 12:07
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('base', '0304_auto_20180705_1115'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='educationgroupyear',
            options={'verbose_name': 'education group year'},
        ),
        migrations.AlterField(
            model_name='groupelementyear',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parents',
                                    to='base.EducationGroupYear'),
        ),
        migrations.AlterField(
            model_name='offerenrollment',
            name='education_group_year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT,
                                    to='base.EducationGroupYear'),
        ),
    ]
