# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-11 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0306_auto_20180709_1334'),
    ]

    operations = [
        # Remove all groupelementyear because it implements OrderModels
        migrations.RunSQL("DELETE FROM base_groupelementyear;"),
        migrations.AlterModelOptions(
            name='groupelementyear',
            options={'ordering': ('order',)},
        ),
        migrations.RemoveField(
            model_name='groupelementyear',
            name='current_order',
        ),
        migrations.AddField(
            model_name='groupelementyear',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
            preserve_default=False,
        ),
    ]
