# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-11 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0307_auto_20180711_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationgrouptype',
            name='changed',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
