# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-17 13:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0308_educationgrouptype_changed'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationgroupyear',
            name='default_learning_unit_enrollment',
            field=models.BooleanField(default=False),
            verbose_name='Weighting'
        ),
        migrations.AddField(
            model_name='educationgroupyear',
            name='weighting',
            field=models.BooleanField(default=False),
            verbose_name='Default learning unit enrollment'
        )
    ]
