# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-11 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('reference', '0017_language_changed'),
        ('base', '0308_educationgrouptype_changed'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationgroupyear',
            name='languages',
            field=models.ManyToManyField(related_name='education_group_years', through='base.EducationGroupLanguage',
                                         to='reference.Language'),
        ),
    ]
