# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-17 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('base', '0308_educationgrouptype_changed'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationgroupyear',
            name='default_learning_unit_enrollment',
            field=models.BooleanField(default=False, verbose_name='Default learning unit enrollment'),
        ),
        migrations.AddField(
            model_name='educationgroupyear',
            name='weighting',
            field=models.BooleanField(default=False, verbose_name='Weighting'),
        ),
    ]
