# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-18 13:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0309_auto_20180717_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationgroupyear',
            name='education_group_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.EducationGroupType', verbose_name='training_type'),
        ),
    ]
