# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-19 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0310_auto_20180718_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupelementyear',
            name='comment',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='comment'),
        ),
        migrations.AlterField(
            model_name='groupelementyear',
            name='comment_english',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='english comment'),
        ),
    ]
