# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-24 06:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0313_remove_learningunityear_mobility_modality'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationgroupyear',
            name='decree_category',
            field=models.CharField(blank=True, choices=[('FCONT', 'FCONT'), ('1BAS', '1BAS'), ('2BAS', '2BAS'), ('AESS', 'AESS'), ('DEC1', 'DEC1'), ('DEC2', 'DEC2'), ('DES', 'DES'), ('DEA', 'DEA'), ('DOC', 'DOC'), ('AES', 'AES'), ('AUTRE', 'AUTRE'), ('BAC', 'BAC'), ('AP2C', 'AP2C'), ('MA1', 'MA1'), ('MA2X', 'MA2X'), ('MA2D', 'MA2D'), ('MA2S', 'MA2S'), ('MA2A', 'MA2A'), ('MA2M', 'MA2M'), ('AS2C', 'AS2C'), ('MACO', 'MACO'), ('AESSB', 'AESSB'), ('CAPS', 'CAPS'), ('AS3C', 'AS3C'), ('FODO', 'FODO'), ('DOCB', 'DOCB'), ('CEMC', 'CEMC'), ('MED', 'MED'), ('VETE', 'VETE')], max_length=40, null=True, verbose_name='Decree category'),
        ),
        migrations.AddField(
            model_name='educationgroupyear',
            name='rate_code',
            field=models.CharField(blank=True, choices=[('NO_ADDITIONAL_FEES', 'NO_ADDITIONAL_FEES'), ('AESS_CAPAES', 'AESS_CAPAES'), ('MINERVAL_COMPLETE', 'MINERVAL_COMPLETE'), ('UNIVERSITY_CERTIFICATE', 'UNIVERSITY_CERTIFICATE'), ('ADVANCED_MASTER_IN_MEDICAL_SPECIALIZATION', 'ADVANCED_MASTER_IN_MEDICAL_SPECIALIZATION'), ('ACCESS_CONTEST', 'ACCESS_CONTEST'), ('UNIVERSITY_CERTIFICATE_30_CREDITS', 'UNIVERSITY_CERTIFICATE_30_CREDITS'), ('CERTIFICATE_MEDECINE_COMPETENCE', 'CERTIFICATE_MEDECINE_COMPETENCE')], max_length=50, null=True, verbose_name='Rate code'),
        ),
    ]
