# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-23 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0313_remove_learningunityear_mobility_modality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupelementyear',
            name='block',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='block'),
        ),
        migrations.AlterField(
            model_name='groupelementyear',
            name='is_mandatory',
            field=models.BooleanField(default=False, verbose_name='mandatory'),
        ),
        migrations.AlterField(
            model_name='groupelementyear',
            name='max_credits',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='max_credits'),
        ),
        migrations.AlterField(
            model_name='groupelementyear',
            name='min_credits',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='min_credits'),
        ),
        migrations.AlterField(
            model_name='groupelementyear',
            name='relative_credits',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='relative credits'),
        ),
        migrations.AlterField(
            model_name='groupelementyear',
            name='sessions_derogation',
            field=models.CharField(choices=[('SESSION_1', 'SESSION_1'), ('SESSION_2', 'SESSION_2'), ('SESSION_3', 'SESSION_3'), ('SESSION_1_2', 'SESSION_1_2'), ('SESSION_1_3', 'SESSION_1_3'), ('SESSION_2_3', 'SESSION_2_3'), ('SESSION_1_2_3', 'SESSION_1_2_3'), ('SESSION_UNDEFINED', 'SESSION_UNDEFINED'), ('SESSION_PARTIAL_2_3', 'SESSION_PARTIAL_2_3')], default='SESSION_UNDEFINED', max_length=65, verbose_name='sessions_derogation'),
        ),
    ]
