# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-25 10:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0316_auto_20180725_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationgroupyear',
            name='secondary_domains',
            field=models.ManyToManyField(related_name='education_group_years', through='base.EducationGroupYearDomain', to='reference.Domain', verbose_name='secondary domains'),
        ),
        migrations.AlterField(
            model_name='groupelementyear',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.EducationGroupYear'),
        ),
    ]
