# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-26 09:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0317_auto_20180725_1229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educationgroupyear',
            name='fee_type',
        ),
    ]
