# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-27 08:46
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0319_auto_20180727_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationgroupyear',
            name='credits',
            field=models.IntegerField(blank=True, null=True, verbose_name='credits'),
        ),
        migrations.AlterField(
            model_name='educationgroupyear',
            name='max_credits',
            field=models.IntegerField(blank=True, null=True, verbose_name='maximum credits'),
        ),
        migrations.AlterField(
            model_name='educationgroupyear',
            name='min_credits',
            field=models.IntegerField(blank=True, null=True, verbose_name='minimum credits'),
        ),
        migrations.AlterField(
            model_name='externallearningunityear',
            name='external_credits',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(500)], verbose_name='local_credits'),
        ),
        migrations.AlterField(
            model_name='groupelementyear',
            name='max_credits',
            field=models.IntegerField(blank=True, null=True, verbose_name='max_credits'),
        ),
        migrations.AlterField(
            model_name='groupelementyear',
            name='min_credits',
            field=models.IntegerField(blank=True, null=True, verbose_name='min_credits'),
        ),
        migrations.AlterField(
            model_name='groupelementyear',
            name='relative_credits',
            field=models.IntegerField(blank=True, null=True, verbose_name='relative credits'),
        ),
        migrations.AlterField(
            model_name='learningunityear',
            name='credits',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(500)], verbose_name='credits'),
        ),
    ]
