# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-08-02 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0324_auto_20180731_0936'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admissionconditionline',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='admissionconditionline',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=False, editable=False),
            preserve_default=False,
        ),
    ]
