# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-08-06 12:34
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('base', '0325_auto_20180802_0954'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidationRule',
            fields=[
                ('field_reference',
                 models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='field reference')),
                ('required_field', models.BooleanField(default=False, verbose_name='required field')),
                ('disabled_field', models.BooleanField(default=False, verbose_name='disabled field')),
                ('initial_value', models.CharField(max_length=255, verbose_name='initial value')),
                ('regex_rule', models.CharField(blank=True, max_length=255, verbose_name='regex rule')),
                ('regex_error_message',
                 models.CharField(blank=True, max_length=255, verbose_name='regex error message')),
            ],
            options={
                'verbose_name': 'validation rule',
            },
        ),
        migrations.AlterModelOptions(
            name='admissionconditionline',
            options={'ordering': ('admission_condition', 'section', 'order')},
        ),
        migrations.AlterField(
            model_name='educationgroupyear',
            name='duration',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='duration'),
        ),
        migrations.AlterField(
            model_name='educationgroupyear',
            name='enrollment_enabled',
            field=models.BooleanField(default=True, verbose_name='enrollment_enabled'),
        ),
        migrations.AlterField(
            model_name='educationgroupyear',
            name='internship',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO'), ('OPTIONAL', 'OPTIONAL')], default='NO',
                                   max_length=20, null=True, verbose_name='internship'),
        ),
        migrations.AlterField(
            model_name='educationgroupyear',
            name='primary_language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reference.Language',
                                    verbose_name='primary_language'),
        ),
    ]
