# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-08-09 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('base', '0327_auto_20180808_1202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='validationrule',
            name='disabled_field',
        ),
        migrations.RemoveField(
            model_name='validationrule',
            name='required_field',
        ),
        migrations.AddField(
            model_name='validationrule',
            name='status_field',
            field=models.CharField(
                choices=[('REQUIRED', 'REQUIRED'), ('ALERT', 'ALERT'), ('NOT_REQUIRED', 'NOT_REQUIRED'),
                         ('DISABLED', 'DISABLED')], default='NOT_REQUIRED', max_length=20),
        ),
        migrations.AlterField(
            model_name='validationrule',
            name='initial_value',
            field=models.CharField(blank=True, max_length=255, verbose_name='initial value'),
        ),
    ]
