# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-08-16 12:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0328_auto_20180809_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admissioncondition',
            name='text_bachelor',
        ),
        migrations.RemoveField(
            model_name='admissioncondition',
            name='text_bachelor_en',
        ),
        migrations.RemoveField(
            model_name='admissioncondition',
            name='text_standard',
        ),
        migrations.RemoveField(
            model_name='admissioncondition',
            name='text_standard_en',
        ),
    ]
