# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-08-10 08:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('base', '0328_auto_20180809_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validationrule',
            name='status_field',
            field=models.CharField(choices=[('REQUIRED', 'REQUIRED'), ('FIXED', 'FIXED'), ('ALERT', 'ALERT'),
                                            ('NOT_REQUIRED', 'NOT_REQUIRED'), ('DISABLED', 'DISABLED')],
                                   default='NOT_REQUIRED', max_length=20),
        ),
    ]
