# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-08-16 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0329_auto_20180810_1023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admissioncondition',
            name='text_bachelor',
        ),
        migrations.RemoveField(
            model_name='admissioncondition',
            name='text_bachelor_en',
        ),
        migrations.RemoveField(
            model_name='admissioncondition',
            name='text_standard',
        ),
        migrations.RemoveField(
            model_name='admissioncondition',
            name='text_standard_en',
        ),
        migrations.AddField(
            model_name='admissioncondition',
            name='text_ca_allegement',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='admissioncondition',
            name='text_ca_allegement_en',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='admissioncondition',
            name='text_ca_bacs_cond_generales',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='admissioncondition',
            name='text_ca_bacs_cond_generales_en',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='admissioncondition',
            name='text_ca_bacs_cond_particulieres',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='admissioncondition',
            name='text_ca_bacs_cond_particulieres_en',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='admissioncondition',
            name='text_ca_bacs_cond_speciales',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='admissioncondition',
            name='text_ca_bacs_cond_speciales_en',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='admissioncondition',
            name='text_ca_bacs_examen_langue',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='admissioncondition',
            name='text_ca_bacs_examen_langue_en',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='admissioncondition',
            name='text_ca_cond_generales',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='admissioncondition',
            name='text_ca_cond_generales_en',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='admissioncondition',
            name='text_ca_maitrise_fr',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='admissioncondition',
            name='text_ca_maitrise_fr_en',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='admissioncondition',
            name='text_ca_ouv_adultes',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='admissioncondition',
            name='text_ca_ouv_adultes_en',
            field=models.TextField(default=''),
        ),
    ]
