# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-08-11 11:35
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0329_auto_20180810_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationgroupyear',
            name='acronym',
            field=models.CharField(db_index=True, max_length=40, validators=[django.core.validators.RegexValidator(regex='^([A-Z]{2,4})([0-9]?)(.*)$')], verbose_name='acronym'),
        ),
        migrations.AlterField(
            model_name='educationgroupyear',
            name='partial_acronym',
            field=models.CharField(db_index=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(regex='^([A-Z]{3,5})([0-9]{3})([A-Z])$')], verbose_name='code'),
        ),
    ]
