# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-08-11 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0330_auto_20180811_1335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educationgroupyear',
            name='max_credits',
        ),
        migrations.RemoveField(
            model_name='educationgroupyear',
            name='min_credits',
        ),
        migrations.AddField(
            model_name='educationgroupyear',
            name='constraint_type',
            field=models.CharField(blank=True, choices=[('CREDITS', 'credits'), ('LEARNING_UNIT_NUMBER', 'Number of learning units')], default='CREDITS', max_length=20, null=True, verbose_name='type of constraint'),
        ),
        migrations.AddField(
            model_name='educationgroupyear',
            name='max_constraint',
            field=models.IntegerField(blank=True, null=True, verbose_name='maximum constraint'),
        ),
        migrations.AddField(
            model_name='educationgroupyear',
            name='min_constraint',
            field=models.IntegerField(blank=True, null=True, verbose_name='minimum constraint'),
        ),
    ]
