# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-08-22 10:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0335_auto_20180822_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationgroupyear',
            name='diploma_printing_title',
            field=models.CharField(blank=True, default='', max_length=140),
        ),
        migrations.AlterField(
            model_name='educationgroupyear',
            name='funding_direction',
            field=models.CharField(blank=True, default='', max_length=1, verbose_name='funding_direction'),
        ),
        migrations.AlterField(
            model_name='educationgroupyear',
            name='funding_direction_cud',
            field=models.CharField(blank=True, default='', max_length=1, verbose_name='cud_funding_direction'),
        ),
        migrations.AlterField(
            model_name='educationgroupyear',
            name='inter_organization_information',
            field=models.CharField(blank=True, default='', max_length=320),
        ),
        migrations.AlterField(
            model_name='educationgroupyear',
            name='keywords',
            field=models.CharField(blank=True, default='', max_length=320, verbose_name='keywords'),
        ),
        migrations.AlterField(
            model_name='educationgroupyear',
            name='professional_title',
            field=models.CharField(blank=True, default='', max_length=320),
        ),
        migrations.AlterField(
            model_name='educationgroupyear',
            name='remark',
            field=models.TextField(blank=True, default='', verbose_name='remark'),
        ),
        migrations.AlterField(
            model_name='educationgroupyear',
            name='remark_english',
            field=models.TextField(blank=True, default='', verbose_name='remark_english'),
        ),
        migrations.AlterField(
            model_name='educationgroupyear',
            name='title_english',
            field=models.CharField(blank=True, default='', max_length=240, verbose_name='title_in_english'),
        ),
    ]
