# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-08-24 10:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0337_auto_20180821_1029'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='educationgroupyear',
            options={'permissions': (('can_change_as_central_manager', 'Can change as central manager'), ('can_change_as_faculty_manager', 'Can change as faculty manager')), 'verbose_name': 'education group year'},
        ),
    ]
