# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-08-28 14:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0338_auto_20180824_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningunityear',
            name='campus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Campus', verbose_name='learning_location'),
        ),
    ]
