# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-08-29 14:13
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0339_auto_20180828_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externallearningunityear',
            name='external_credits',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(500)], verbose_name='local_credits'),
        ),
        migrations.AlterField(
            model_name='learningunityear',
            name='credits',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(500)], verbose_name='credits'),
        ),
    ]
