# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-08-30 15:37
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0340_auto_20180829_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prerequisite',
            name='prerequisite',
            field=models.CharField(blank=True, default='', max_length=240, validators=[django.core.validators.RegexValidator(message='Prerequisites are invalid', regex='^(|[BLMWX][A-Z]{2,4}\\d{4}[A-Z0-9]{0,1}|([BLMWX][A-Z]{2,4}\\d{4}[A-Z0-9]{0,1}|\\([BLMWX][A-Z]{2,4}\\d{4}[A-Z0-9]{0,1}( OU [BLMWX][A-Z]{2,4}\\d{4}[A-Z0-9]{0,1})+\\))( ET ([BLMWX][A-Z]{2,4}\\d{4}[A-Z0-9]{0,1}|\\([BLMWX][A-Z]{2,4}\\d{4}[A-Z0-9]{0,1}( OU [BLMWX][A-Z]{2,4}\\d{4}[A-Z0-9]{0,1})+\\)))+|([BLMWX][A-Z]{2,4}\\d{4}[A-Z0-9]{0,1}|\\([BLMWX][A-Z]{2,4}\\d{4}[A-Z0-9]{0,1}( ET [BLMWX][A-Z]{2,4}\\d{4}[A-Z0-9]{0,1})+\\))( OU ([BLMWX][A-Z]{2,4}\\d{4}[A-Z0-9]{0,1}|\\([BLMWX][A-Z]{2,4}\\d{4}[A-Z0-9]{0,1}( ET [BLMWX][A-Z]{2,4}\\d{4}[A-Z0-9]{0,1})+\\)))+)$')]),
        ),
    ]
