# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-08-30 16:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0341_auto_20180830_1537'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='educationgroupyear',
            options={'verbose_name': 'education group year'},
        ),
    ]
