# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-09-03 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0342_auto_20180830_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationgrouptype',
            name='name',
            field=models.CharField(choices=[('Agregation', 'Agregation'), ('Certificate of participation', 'Certificate of participation'), ('Certificate of success', 'Certificate of success'), ('Certificate of holding credits', 'Certificate of holding credits'), ('Bachelor', 'Bachelor'), ('Certificat', 'Certificat'), ('CAPAES', 'CAPAES'), ('Research certificat', 'Research certificat'), ('University first cycle certificat', 'University first cycle certificat'), ('University second cycle certificat', 'University second cycle certificat'), ('Access contest', 'Access contest'), ('Language classes', 'Language classes'), ('Isoldated classes', 'Isoldated classes'), ('PHD', 'PHD'), ('Formation PHD', 'Formation PHD'), ('Junior year', 'Junior year'), ('Program master 120', 'Program master 120'), ('Master MA 120', 'Master MA 120'), ('Master MD 120', 'Master MD 120'), ('Master MS 120', 'Master MS 120'), ('Program master 180-240', 'Program master 180-240'), ('Master MA 180-240', 'Master MA 180-240'), ('Master MD 180-240', 'Master MD 180-240'), ('Master MS 180-240', 'Master MS 180-240'), ('Master in 60 credits', 'Master in 60 credits'), ('Master of specialist', 'Master of specialist'), ('Internship', 'Internship'), ('Deepening', 'Deepening'), ('Sociaty minor', 'Sociaty minor'), ('Access minor', 'Access minor'), ('Open minor', 'Open minor'), ('Disciplinary complement minor', 'Disciplinary complement minor'), ('FSA speciality', 'FSA speciality'), ('Option', 'Option'), ('Mobility partnership', 'Mobility partnership'), ('Common core', 'Common core'), ('Minor list choice', 'Minor list choice'), ('Major list choice', 'Major list choice'), ('Option list choice', 'Option list choice'), ('Finality 120 list choice', 'Finality 120 list choice'), ('Finality 180 list choice', 'Finality 180 list choice'), ('Mobility partnership list choice', 'Mobility partnership list choice'), ('Complementary module', 'Complementary module'), ('Sub group', 'Sub group')], max_length=255, verbose_name='training_type'),
        ),
    ]
