# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-09-07 09:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0344_auto_20180903_1613'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='learningunityear',
            managers=[
            ],
        ),
    ]
