# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-09-11 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0345_auto_20180907_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationgrouptype',
            name='category',
            field=models.CharField(choices=[('TRAINING', 'TRAINING'), ('MINI_TRAINING', 'MINI_TRAINING'), ('GROUP', 'GROUP')], default='TRAINING', max_length=25, verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='educationgrouptype',
            name='name',
            field=models.CharField(max_length=255, verbose_name='training_type'),
        ),
    ]
