# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-09-12 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0346_auto_20180911_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationgroupyear',
            name='internal_comment',
            field=models.TextField(blank=True, max_length=500, verbose_name='comment (internal)'),
        ),
    ]
