# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-09-12 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0346_auto_20180911_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationgroupyear',
            name='constraint_type',
            field=models.CharField(blank=True, choices=[('CREDITS', 'credits'), ('NUMBER_OF_ELEMENTS', 'Number of elements')], default=None, max_length=20, null=True, verbose_name='type of constraint'),
        ),
    ]
