# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-09-13 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0348_educationgroupyear_internal_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationgroupyear',
            name='duration_unit',
            field=models.CharField(blank=True, choices=[('QUADRIMESTER', 'QUADRIMESTER'), ('TRIMESTER', 'TRIMESTER'), ('MONTH', 'MONTH'), ('WEEK', 'WEEK'), ('DAY', 'DAY')], default='QUADRIMESTER', max_length=40, null=True, verbose_name='duration unit'),
        ),
    ]
