# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-09-14 11:14
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0020_domain_changed'),
        ('base', '0349_auto_20180913_1021'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationGroupAchievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False)),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('changed', models.DateTimeField(auto_now=True, null=True)),
                ('code_name', models.CharField(max_length=100, verbose_name='code')),
                ('text', ckeditor.fields.RichTextField(null=True, verbose_name='text')),
                ('education_group_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.EducationGroupYear')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reference.Language')),
            ],
            options={
                'verbose_name': 'education group achievement',
            },
        ),
        migrations.CreateModel(
            name='EducationGroupDetailedAchievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False)),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('changed', models.DateTimeField(auto_now=True, null=True)),
                ('code_name', models.CharField(max_length=100, verbose_name='code')),
                ('text', ckeditor.fields.RichTextField(null=True, verbose_name='text')),
                ('education_group_achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.EducationGroupAchievement')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reference.Language')),
            ],
            options={
                'verbose_name': 'education group detailed achievement',
            },
        ),
        migrations.AlterUniqueTogether(
            name='educationgroupdetailedachievement',
            unique_together=set([('code_name', 'education_group_achievement', 'language')]),
        ),
        migrations.AlterUniqueTogether(
            name='educationgroupachievement',
            unique_together=set([('code_name', 'education_group_year', 'language')]),
        ),
    ]
