# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-09-19 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0352_auto_20180914_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationgroupyear',
            name='english_activities',
            field=models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO'), ('OPTIONAL', 'OPTIONAL')], max_length=20, null=True, verbose_name='activities in English'),
        ),
    ]
