# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-09-20 15:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0355_message_template_luys_automatic_postponement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningachievement',
            name='learning_unit_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.LearningUnitYear', verbose_name='learning unit year'),
        ),
    ]
