# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-09-20 15:03
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0355_message_template_luys_automatic_postponement'),
    ]

    operations = [

        migrations.AddField(
            model_name='educationgroupachievement',
            name='english_text',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='text in English'),
        ),
        migrations.AddField(
            model_name='educationgroupachievement',
            name='french_text',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='text in French'),
        ),
        migrations.AddField(
            model_name='educationgroupdetailedachievement',
            name='english_text',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='text in English'),
        ),
        migrations.AddField(
            model_name='educationgroupdetailedachievement',
            name='french_text',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='text in French'),
        ),
        migrations.AlterField(
            model_name='learningachievement',
            name='learning_unit_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.LearningUnitYear', verbose_name='learning unit year'),
        ),
        migrations.RemoveField(
            model_name='educationgroupachievement',
            name='text',
        ),
        migrations.AlterUniqueTogether(
            name='educationgroupachievement',
            unique_together=set([('code_name', 'education_group_year')]),
        ),
        migrations.RemoveField(
            model_name='educationgroupdetailedachievement',
            name='text',
        ),
        migrations.AlterUniqueTogether(
            name='educationgroupdetailedachievement',
            unique_together=set([('code_name', 'education_group_achievement')]),
        ),
        migrations.RemoveField(
            model_name='educationgroupachievement',
            name='language',
        ),
        migrations.RemoveField(
            model_name='educationgroupdetailedachievement',
            name='language',
        ),
    ]
