# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-09-20 16:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0356_auto_20180920_1542'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='educationgroupachievement',
            options={'ordering': ('order',), 'verbose_name': 'education group achievement'},
        ),
        migrations.AlterModelOptions(
            name='educationgroupdetailedachievement',
            options={'ordering': ('order',), 'verbose_name': 'education group detailed achievement'},
        ),
    ]
