# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-10-01 13:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0359_message_template_luys_automatic_postponement_update'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateAim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('changed', models.DateTimeField(auto_now=True, null=True)),
                ('section', models.PositiveIntegerField(db_index=True, verbose_name='section')),
                ('description', models.CharField(db_index=True, max_length=1024, unique=True, verbose_name='description')),
            ],
        ),
        migrations.CreateModel(
            name='EducationGroupCertificateAim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('changed', models.DateTimeField(auto_now=True, null=True)),
                ('certificate_aim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.CertificateAim')),
                ('education_group_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.EducationGroupYear')),
            ],
        ),
    ]
