# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-10-03 13:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0360_auto_20180928_1042'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateAim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('changed', models.DateTimeField(auto_now=True, null=True)),
                ('code', models.PositiveIntegerField(db_index=True, unique=True, verbose_name='aim number')),
                ('section', models.PositiveIntegerField(db_index=True, verbose_name='section')),
                ('description', models.CharField(db_index=True, max_length=1024, unique=True, verbose_name='description')),
            ],
        ),
        migrations.CreateModel(
            name='EducationGroupCertificateAim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('changed', models.DateTimeField(auto_now=True, null=True)),
                ('certificate_aim', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.CertificateAim')),
                ('education_group_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.EducationGroupYear')),
            ],
        ),
        migrations.AlterField(
            model_name='admissionconditionline',
            name='access',
            field=models.CharField(choices=[('-', '-'), ('on_the_file', 'On the file: direct access or access with additional training'), ('direct_access', 'Direct Access'), ('access_with_training', 'Access with additional training')], default='-', max_length=32),
        ),
        migrations.AddField(
            model_name='educationgroupyear',
            name='certificate_aims',
            field=models.ManyToManyField(related_name='education_group_years', through='base.EducationGroupCertificateAim', to='base.CertificateAim'),
        ),
    ]
