# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-10-04 10:38
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0362_auto_20181003_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationgroupyear',
            name='duration',
            field=models.IntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='duration'),
        ),
    ]
