# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-10-05 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0363_auto_20181004_1038'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificateaim',
            options={'ordering': ('code', 'section')},
        ),
        migrations.AddField(
            model_name='educationgrouporganization',
            name='is_producing_annexe',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='educationgrouporganization',
            name='is_producing_cerfificate',
            field=models.BooleanField(default=False),
        ),
    ]
