# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-10-09 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0364_auto_20181005_1215'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificateaim',
            options={'ordering': ('section', 'code')},
        ),
        migrations.AlterField(
            model_name='educationgroupyear',
            name='certificate_aims',
            field=models.ManyToManyField(blank=True, related_name='education_group_years', through='base.EducationGroupCertificateAim', to='base.CertificateAim'),
        ),
    ]
