# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-10-10 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0365_auto_20181009_1547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='acronym',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='code',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='name',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='prefix',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='website',
        ),
        migrations.AddField(
            model_name='entityversion',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='organization_logos', verbose_name='logo'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='type',
            field=models.CharField(blank=True, choices=[('MAIN', 'MAIN'), ('ACADEMIC_PARTNER', 'ACADEMIC_PARTNER'), ('INDUSTRIAL_PARTNER', 'INDUSTRIAL_PARTNER'), ('SERVICE_PARTNER', 'SERVICE_PARTNER'), ('COMMERCE_PARTNER', 'COMMERCE_PARTNER'), ('PUBLIC_PARTNER', 'PUBLIC_PARTNER')], default='', max_length=30),
            preserve_default=False,
        ),
    ]
