# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-10-17 11:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0367_auto_20181017_1141'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='educationgroupcertificateaim',
            unique_together=set([('education_group_year', 'certificate_aim')]),
        ),
    ]
