# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-10-18 09:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0374_auto_20181018_0946'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='educationgrouporganization',
            unique_together=set([('education_group_year', 'organization')]),
        ),
    ]
