# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-13 15:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0033_messages_templates_populate'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='assistants_contract_end_ending_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='assistants_contract_end_starting_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
